window.EFTForge = window.EFTForge || {};

const _TRANSLATIONS = {
    en: {
        // Header
        "btn.about":            "About",
        "btn.builds":           "Builds",
        "btn.news":             "News",
        // News page
        "news.title":           "NEWS",
        "news.loading":         "Loading...",
        "news.loadError":       "Could not load content. Please check your connection.",
        "news.postNotFound":    "Post not found.",
        "news.noPosts":         "No posts yet. Check back soon.",
        "news.backToList":      "Back to News",
        "ui.close":             "Close",
        "ui.newBadge":          "New!",
        // Weapon selector toggles
        "btn.primary":          "Primary",
        "btn.pistol":           "Pistol",
        "btn.caliber":          "Caliber",
        "btn.class":            "Class",
        // Left build area buttons
        "btn.back":             "\u2190 Back",
        "btn.backShort":        "Back",
        "btn.resetShort":       "Reset",
        "btn.stripShort":       "Strip",
        "btn.saveShareShort":   "Save",
        "btn.gunBuildsShort":   "Explore",
        "btn.reset":            "Reset Build",
        "btn.strip":            "Strip Build",
        "btn.saveShare":        "Save / Share",
        "btn.gunBuilds":        "Explore Builds",
        // Search placeholders
        "placeholder.gunSearch":  "Start typing to search...",
        "placeholder.attSearch":  "Start typing to search...",
        // Right panel placeholder
        "placeholder.modding":    "Select an attachment slot to begin modding...",
        "placeholder.rightClick": "Right click an attachment to remove it",
        "placeholder.longPress":  "Swipe left on an installed attachment to remove it",
        // Mobile tab bar
        "tab.build":               "Build",
        "tab.attachments":         "Attachments",
        "modal.installAttachment": "Install Attachment",
        "modal.weight":            "WEIGHT",
        "modal.recoil":            "RECOIL %",
        "modal.ergo":              "ERGONOMICS",
        "modal.evoErgo":           "EVO ERGO",
        "modal.cancel":            "Cancel",
        "modal.install":           "Install",
        "modal.remove":            "Remove",
        // Stats panel
        "stats.title":              "CURRENT BUILD",
        "stats.compareMode":        "COMPARE MODE",
        "stats.ergo":               "Ergonomics",
        "stats.verRecoil":          "Ver. Recoil",
        "stats.horRecoil":          "Hor. Recoil",
        "stats.accuracy":           "Accuracy",

        "stats.weight":             "Weight:",
        "stats.sightingRange":      "Sighting Range:",
        "stats.muzzleVelocity":     "Muzzle Velocity:",
        "stats.noAmmo":             "No Ammo",
        "stats.eed":                "EvoErgoDelta",
        "stats.eedLabel":           "EED:",
        "stats.eedLabelShort":      "EED:",
        "stats.overswing":          "OverSwing:",
        "stats.armStamina":         "Arm Stamina",
        "stats.fullMag":            "Assume Full Magazine",
        "stats.ammoDisabledTitle":  "Selection Disabled",
        "stats.ammoDisabledTip":    "Assume Full Magazine is off",
        "stats.strengthLv":         "Strength Level",
        "stats.selectWeapon":       "Select a weapon to begin",
        "stats.staminaDisclaimer":  "Seconds until arm stamina depletes while standing.\nExpected deviation \u00B10.5s",
        "stats.eedDesc":            "Unlike base ergonomics, EED accounts for equipment weight. Two builds with the same EED will handle identically (same overswing behavior and ADS speed, excluding variables such as your character's skill levels, etc). Your character's weight affects ADS speed but not overswing. Set your Equipment Ergonomics Modifier to get accurate results.",
        "stats.overswingDesc":      "Whether the gun will swing over the center point of aiming after ADS. Occurs when EED is negative. Estimated inaccuracy of \u00B12 EED.",
        "stats.equipErgoLabel":     "Equipment Ergonomics Modifier",
        "stats.equipErgoDisclaimer":"The total Ergonomics penalty from worn equipment (headgear, armor, backpack, rig, facecover, eyewear) - set this to match your in-game gear.",
        "stats.eedWarnTooltip":         "EED is close to the overswing threshold. If your equipment reduces ergonomics, this build may overswing - consider setting your Equipment Ergonomics Modifier.",
        "stats.configEquipErgoTooltip": "Configure equipment ergonomics modifier",
        "stats.configStrengthTooltip":  "Configure strength level",
        "stats.yes":                "YES",
        "stats.no":                 "NO",
        // Advanced stats
        "hidden.showBtn":           "Show advanced stats",
        "hidden.hideBtn":           "Hide advanced stats",
        "hidden.title":             "ADVANCED STATS",
        "hidden.heatFactor":        "Heat Factor",
        "hidden.coolingFactor":     "Cooling Factor",
        "hidden.durabilityBurn":    "Durability Burn",
        "hidden.aimPlane":          "Aim Deviation",
        "hidden.aimSens":           "Aim Sensitivity",
        "hidden.camAngleStep":      "Camera Angle Step",
        "hidden.camSnap":           "Camera Snap",
        "hidden.mountCamSnap":      "Mount Camera Snap",
        "hidden.mountHRec":         "Mount Horizontal Recoil",
        "hidden.mountVRec":         "Mount Vertical Recoil",
        "hidden.mountBreath":       "Mount Breath Sway",
        "hidden.devCurve":          "Deviation Curve",
        "hidden.devMax":            "Max Deviation",
        "hidden.recAngle":          "Recoil Angle",
        "hidden.recHandRot":        "Hand Rotation",
        "hidden.recDispersion":     "Recoil Dispersion",
"hidden.recReturnSpeed":    "Recoil Return Speed",
        "hidden.tip.aimPlane":      "Base spread of the weapon when aiming down sights",
        "hidden.tip.aimSens":       "How sharply the camera responds to mouse input while aiming",
        "hidden.tip.camAngleStep":  "Increment at which the camera angle snaps per step",
        "hidden.tip.camSnap":       "How quickly the camera returns to center after recoil",
        "hidden.tip.devCurve":      "The curve function applied to shot deviation over time",
        "hidden.tip.devMax":        "Maximum possible deviation from point of aim",
        "hidden.tip.mountCamSnap":  "Multiplier for how aggressively the camera re-centers while mounted",
        "hidden.tip.mountHRec":     "Recoil multiplier applied when firing from a mount, horizontal axis",
        "hidden.tip.mountVRec":     "Recoil multiplier applied when firing from a mount, vertical axis",
        "hidden.tip.mountBreath":   "Sway multiplier for out-of-breath penalty while mounted",
        "hidden.tip.recAngle":      "Angle offset direction of the recoil pattern",
        "hidden.tip.recHandRot":    "Recoil hand rotation multiplier category",
        "hidden.tip.recDispersion": "Spread applied to successive shots in the recoil pattern",
"hidden.tip.recReturnSpeed":"How quickly the weapon returns to its base position between shots",
        "hidden.tip.heatFactor":    "Combined multiplier of every installed mod and the selected ammo's heat buildup per shot",
        "hidden.tip.coolingFactor": "Combined multiplier of every installed mod's cooling rate between shots",
        "hidden.tip.durabilityBurn": "Combined multiplier of every installed mod and the selected ammo's durability burn per shot",
        "hidden.tooltip":           "Stats marked ? are unavailable for weapons not yet in the game data source",
        // Price view
        "stats.buildCost":          "BUILD COST",
        "stats.pveModeLabel":       "PVE",
        "stats.totalCost":          "Total",
        "stats.ammoRow":            "Ammo",
        "stats.ubglAmmoRow":        "UBGL Ammo",
        "stats.buildView":          "Build",
        "stats.factoryIncluded":    "Factory",
        "stats.baseReceiver":       "Base Receiver",
        "stats.baseFactoryPreset":  "Factory Preset",
        "stats.priceView":          "Price",
        "stats.fleaMarket":         "Fetching Flea Market Info",
        "stats.fleaLabel":          "Flea",
        "stats.fleaTs":             "Last Flea Fetch:",
        "stats.refetchFlea":        "Refetch Flea",
        "stats.refetchingFlea":     "Refetching",
        "stats.fetchingFleaPrices": "Fetching Flea Prices",
        "stats.fleaFetching":       "Fetching prices for",
        "stats.fleaFetchingItems":  "items...",
        "stats.fleaCached":         "All prices cached.",
        "stats.fleaUpdated":        "Prices updated.",
        "stats.traderLevels":       "Set Trader Levels",
        "stats.traderLevelsAll":    "All",
        // Attachment tree
        "tree.title":             "WORKBENCH",
        "tree.swipeHint":         "Swipe left to remove attachment",
        // Attachment table column headers
        "th.name":                "Name",
        "th.weight":              "Weight (kg)",
        "th.recoil":              "Recoil",
        "th.recoilList":          "Recoil Mod.",
        "th.recoilCombo":         "Recoil %Change",
        "th.recoilTooltipList":   "The item's in-game recoil modifier, the same value the attachment's in-game inspect menu shows.",
        "th.recoilTooltipCombo":  "Actual % recoil change on your current build.\nDiffers from the item's raw recoilModifier stat because other installed mods already reduced the base recoil, making each additional reduction a larger share of what remains.",
        "th.ergo":                "Ergonomics",
        "th.accuracy":            "Accuracy",
        "th.evoErgo":             "EvoErgo",
        "th.rubRecoil":           "₽/Recoil",
        "th.rubRecoilTooltip":    "Total combo price / recoilModifier. Lower = cheaper per point of recoil reduction.",
        "th.balance":             "R+E",
        "th.balanceTooltip":      "Sorts by a combined recoil + ergo score.\nUse the slider to control how much you're willing to sacrifice recoil for ergonomics.\nSlider all the way left = pure recoil priority. All the way right = pure ergo priority.",
        "ui.balanceRecoil":       "Recoil",
        "ui.balanceErgo":         "Ergo",
        "th.price":               "Price",
        "th.priceTooltip":        "To switch between PvP and PvE pricing, open the Price panel and toggle PvE mode",
        "th.heatCoolBurn":        "Heat/Cool/Burn",
        "th.muzzleVelocity":      "Velocity",
        // Build manager modals
        "modal.save":             "SAVE BUILD",
        "modal.share":            "SHARE BUILD",
        "modal.import":           "IMPORT BUILD",
        "modal.backup":           "BACKUP",
        "modal.builds":           "SAVED BUILDS",
        "modal.exploreBuilds":    "EXPLORE BUILDS",
        "modal.myBuilds":         "MY BUILDS",
        "modal.communityBuilds":  "COMMUNITY BUILDS",
        "modal.publishBtn":       "Publish",
        "modal.publishedBtn":     "Published",
        "modal.unlistBtn":        "Unlist",
        "modal.noPublicBuilds":   "No community builds yet. Be the first!",
        "modal.publicBuildsError": "Could not load community builds.",
        "modal.communityBuildsUnavailable": "Community builds are currently unavailable. Please try again later.",
        "modal.publishLoading":   "Loading community builds...",
        "modal.anonymousAuthor":  "Tarkov Citizen",
        "cb.featured":            "Featured",
        "cb.statWeight":          "Weight",
        "cb.statOverswing":       "Overswing",
        "cb.statCost":            "Cost",
        "cb.statsNote":           "Stats snapshotted at time of publish",
        "cb.loads":               "loads",
        "cb.comments":            "Comments",
        "cb.noComments":          "No comments yet.",
        "cb.commentsLoading":     "Loading...",
        "cb.commentsError":       "Failed to load comments.",
        "cb.commentPlaceholder":  "Write a comment...",
        "cb.commentSubmit":       "Post",
        "cb.commentError":        "Failed to post comment.",
        "cb.deleteCommentFailed": "Failed to delete comment.",
        "cb.infoTooltip":         "Community builds are loadouts shared by players for this specific weapon.\n\nSave a build under Save / Share and hit Publish to share yours with the community.\n\nOutstanding builds can be featured by the admin, so make it count!\n\nCheck the Leaderboard to see the top trending and all-time builds. Give your favorites a like so they make the cut!",
        "cb.limitReachedTitle":   "Build Limit Reached",
        "cb.limitReachedMsg":     "This gun has reached the community builds limit. Please contact the website owner to resolve this.",
        "cb.searchPlaceholder":   "Search builds...",
        "cb.noMatch":             "No community builds match your search.",
        "cb.sort.default":        "Default",
        "cb.sort.newest":         "Newest",
        "cb.sort.loads":          "Most Loaded",
        "cb.sort.rating":         "Highest Rated",
        "cb.sort.eed":            "Highest EED",
        "cb.sort.recoil":         "Best V.Recoil",
        "cb.sort.price":          "Cheapest",
        "modal.saveName":         "Build name...",
        "modal.saveBtn":          "Save",
        "modal.tagFilterLabel":   "Filter by tag:",
        "tag.meta":               "Meta",
        "tag.budget":             "Budget",
        "tag.cqb":                "CQB",
        "tag.sniper":             "Long Range",
        "tag.recoil":             "Recoil",
        "tag.ergo":               "Ergo",
        "tag.pve":                "PvE",
        "tag.beginner":           "Beginner",
        "tag.hybrid":             "Hybrid",
        "modal.copyBtn":          "Copy Share Code",
        "modal.copied":           "Copied!",
        "modal.pasteBtn":         "Paste",
        "modal.importBtn":        "Import",
        "modal.exportBtn":        "Export Backup",
        "modal.importFile":       "Import from File",
        "modal.dropToImport":     "Drop file to import",
        "modal.searchBuilds":     "Search by build name or weapon...",
        "modal.searchBuildsGun":  "Search by build name...",
        "modal.noBuilds":         "No saved builds yet.",
        "modal.publishHint":      "To publish a build, save it first, then use the Publish button below.",
        "modal.publishHintMobile": "Publishing community builds is not supported on mobile.",
        "modal.noMatch":          "No builds match your search.",
        "modal.saveAndShare":     "SAVE & SHARE",
        "modal.pasteBuildCode":   "Paste build code to import...",
        "modal.alreadyExists":    " already exists for this weapon.",
        "modal.overwriteConfirm": "Do you want to overwrite it?",
        "modal.restoreTitle":     "Unfinished Build",
        "modal.restoreSubtitle":  "You were mid-build on this weapon. Continue where you left off?",
        "modal.restoreContinue":  "Continue",
        "modal.restoreAbandon":   "Abandon",
        "modal.discardTitle":     "UNSAVED CHANGES",
        "modal.discardSubtitle":  "You have unsaved changes. Are you sure you want to discard them?",
        "modal.discardConfirm":   "Yes",
        "modal.discardCancel":    "No",
        "modal.importBackup":     "IMPORT BACKUP",
        "modal.importMode":       "IMPORT MODE",
        "modal.backupInfo":       "{n} build(s) from version {v}",
        "modal.mergeBtn":         "Merge into Existing",
        "modal.overwriteAllBtn":  "Overwrite All",
        "modal.versionMismatch":  "\u26A0 Version Mismatch",
        "modal.versionMismatchDesc": "This backup was created with {version} (current: {current}). It may cause issues.",
        "modal.areYouSure":       "ARE YOU SURE?",
        "modal.nameConflicts":    "NAME CONFLICTS",
        "modal.conflictsDesc":    "These builds already exist. Choose how to handle each one.",
        "modal.conflict":         "conflict",
        "modal.conflicts":        "conflicts",
        "modal.confirmAll":       "Confirm All",
        "modal.newBuildName":     "New build name...",
        "modal.nameEmpty":        "Name cannot be empty.",
        "modal.nameTaken":        "That name already exists for this weapon.",
        "modal.nameDuplicate":    "Duplicate rename within this import.",
        // Profile
        "profile.title":              "MY PROFILE",
        "profile.username":           "Display Name",
        "profile.usernamePlaceholder":"Tarkov Citizen",
        "profile.usernameHint":           "Shown on builds and comments you publish. Leave blank to stay anonymous.",
        "profile.usernameInvalidChars":   "Only letters, numbers, spaces, - _ . are allowed.",
        "profile.changeAvatar":       "Change",
        "profile.save":               "Save",
        "profile.cancel":             "Cancel",
        "profile.saving":             "Saving...",
        "profile.savedTitle":         "Profile Saved",
        "profile.savedMsg":           "Your display name and avatar have been updated.",
        "profile.avatarSelected":     "Image ready - will upload on save.",
        "profile.avatarUploading":    "Uploading avatar...",
        "profile.avatarError":        "Avatar upload failed.",
        "profile.avatarTooLarge":     "Image must be under 2 MB.",
        "profile.cropTitle":          "ADJUST PROFILE PICTURE",
        "profile.cropHint":           "Drag to reposition - Scroll to zoom",
        "profile.cropConfirm":        "Apply",
        "profile.navLabel":           "Profile",
        "profile.accountSection":     "PROFILE",
        "profile.accountId":          "UUID",
        "profile.revealId":           "Reveal",
        "profile.revealWarning":      "Your UUID is your password. Anyone with it can claim your community builds and comments.",
        "profile.revealConfirm":      "Confirm Reveal",
        "profile.copyId":             "Copy",
        "profile.hideId":             "Hide",
        "profile.copied":             "Copied!",
        "profile.restoreDevice":      "Relink community data",
        "profile.transferTitle":      "RELINK COMMUNITY DATA",
        "profile.transferLabel":      "Enter your UUID from the old device:",
        "profile.transferPlaceholder":"xxxxxxxx-xxxx-4xxx-xxxx-xxxxxxxxxxxx",
        "profile.transferPreview":    "Preview",
        "profile.transferPreviewing": "Checking...",
        "profile.transferNoData":     "No data found for that UUID.",
        "profile.transferSelf":       "That is your current UUID.",
        "profile.transferBuilds":     "builds",
        "profile.transferComments":   "comments",
        "profile.transferFromOld":    "from old profile",
        "profile.transferUnaffected": "already on this profile, unaffected",
        "profile.transferWillTitle":  "Will be transferred to your current profile:",
        "profile.transferWontTitle":  "Cannot transfer (stored locally in old browser):",
        "profile.transferWont1":      "Favorited attachments",
        "profile.transferWont2":      "Locally saved builds",
        "profile.transferAlert":      "Anyone on the previous device or browser will have their community builds and comments unlinked from that instance.",
        "profile.transferBack":       "Back",
        "profile.transferConfirm":    "Confirm Transfer",
        "profile.transferring":       "Transferring...",
        "profile.transferDoneTitle":  "Transfer Complete",
        "profile.transferDoneMsg":    "builds and comments have been moved to your profile.",
        "profile.profileRateLimit":   "Too many requests. Please wait a moment before trying again.",
        "profile.transferError":      "Invalid or unverifiable UUID.",
        "profile.transferFailed":     "Transfer failed. Please try again.",
        // About dialog
        "about.title":            "ABOUT EFTForge",
        "about.reportBug":        "Report Bug",
        "about.disclaimer1":      "Game content and materials are trademarks and copyrights of <strong style=\"color:#bbb;\">Battlestate Games</strong> and its licensors. All rights reserved.",
        "about.disclaimer2":      "EFTForge is an unofficial tool and is not affiliated with, endorsed by, or in any way officially connected with <strong style=\"color:#bbb;\">Battlestate Games</strong>.",
        "about.dataSource":       "All in-game data is sourced from the",
        "about.copyright":        "\u00A9 2026 Morph1ne. All Rights Reserved.",
        "about.donateShow":       "Support the Project!",
        "about.donateHide":       "Hide Payment Codes",
        "about.donateWechat":     "WeChat Payment Code",
        "about.donateAlipay":     "Alipay Payment Code",
        "about.donateDisclaimer": "100% of donations go directly towards project maintenance.",
        "about.checkForUpdates":  "Check for Updates",
        "about.checking":         "Checking...",
        "about.upToDate":         "You're up to date.",
        "about.updateAvailable":  "Update available!",
        "about.updateNow":        "Update Now",
        "about.updateServerError":"Could not reach server.",
        // Toast messages
        "toast.savedTitle":           "Build Saved",
        "toast.savedMsg":             "Your build has been saved.",
        "toast.resetTitle":           "Build Reset",
        "toast.resetMsg":             "Build has been reset to factory.",
        "toast.strippedTitle":        "Build Stripped",
        "toast.strippedMsg":          "All attachments removed.",
        "toast.importedTitle":        "Build Imported",
        "toast.importedMsg":          "Build successfully imported.",
        "toast.exportedTitle":        "Backup Exported",
        "toast.exportedMsg":          "All builds exported.",
        "toast.exportedCountMsg":     "{n} build(s) saved to file.",
        "toast.noBuildsToExportTitle": "Nothing to Export",
        "toast.noBuildsToExport":     "No saved builds to export.",
        "modal.deletePublishedTitle": "DELETE PUBLISHED BUILD",
        "modal.deletePublishedBody":  "This build is published to the community. Deleting it will also remove it from the community builds list.",
        "modal.deleteAndUnlist":      "Delete & Unlist",
        "toast.deletedTitle":         "Build Deleted",
        "toast.invalidCode":          "Invalid share code.",
        "toast.invalidFile":          "Invalid backup file.",
        "toast.connectionError":      "Server Unavailable",
        "toast.backendDown":          "Could not load weapon list.",
        "toast.ammoLoadFailed":       "Could not load ammo data.",
        "toast.serverUnreachable":    "Could not reach the server.",
        "toast.attachListFailed":     "Could not load attachment list.",
        "toast.attachDataFailed":     "Could not load attachment data.",
        "toast.networkHintDev":       "Is the backend running?",
        "toast.networkHintProd":      "The server may be down or under maintenance.",
        "toast.syncNoticeTitle":      "Daily Data Sync",
        "toast.syncNoticeMsg":        "The server is resyncing tarkov.dev data at 4:00 AM UTC+8. The site may be briefly unavailable (~1 minute).",
        "toast.syncRunningTitle":     "Data Sync in Progress...",
        "toast.syncRunningMsg":       "The server is resyncing tarkov.dev data. Some data may be temporarily unavailable.",
        "toast.storageFull":          "Storage Full",
        "toast.storageFullMsg":       "Delete some saved builds to make room.",
        "toast.saveFailed":           "Save Failed",
        "toast.saveFailedMsg":        "Please enter a build name.",
        "toast.codeCopiedMsg":        "Build code copied to clipboard.",
        "toast.copyFailed":           "Copy Failed",
        "toast.clipboardFailed":      "Could not access clipboard.",
        "toast.loadFailed":           "Load Failed",
        "toast.codeCorrupted":        "Build code is corrupted.",
        // Publish / unlist toasts
        "toast.publishSuccess":       "Build Published",
        "toast.publishSuccessMsg":    "Your build is now live for the community!",
        "toast.publishFailed":        "Publish Failed",
        "toast.publishRateLimit":     "Please wait before publishing again. (1 minute)",
        "toast.publishLimitReached":  "This gun has reached the community builds limit (500). Please contact the website owner to resolve this.",
        "toast.publishBanned":        "You are banned from publishing builds.",
        "toast.unlistSuccess":        "Build Unlisted",
        "toast.unlistSuccessMsg":     "Your build has been removed from the community.",
        "toast.unlistFailed":         "Unlist Failed",
        // Publish confirm panel
        "publish.confirm":            "You are about to publish this build for all players.",
        "publish.confirmSub":         "Once published, it cannot be edited.",
        "publish.nameWarning":        "WARNING! Your custom build name will be public and linked to your identity. Offensive, illegal, or abusive names will be traced back to you by the admin and there will be consequences.",
        "publish.btnCancel":          "Cancel",
        "publish.btnModify":          "Modify",
        "publish.btnConfirm":         "Confirm Publish",
        "publish.publishing":         "Publishing...",
        "publish.mobileTray":         "Review & Publish",
        "publish.slotLockedTitle":    "Reviewing Build",
        "publish.slotLockedMsg":      "You are in publish confirmation. Click Modify to change attachments.",
        // Admin push notifications
        "notify.bannedTitle":         "Publishing Restricted",
        "notify.banned":              "You have been temporarily banned from publishing builds. Duration: {duration}. You will be unbanned on {date}.",
        "notify.bannedPermanent":     "You have been permanently banned from publishing builds.",
        "notify.banReason":           "Reason: {reason}",
        "notify.unbannedTitle":       "Publishing Restored",
        "notify.unbanned":            "Your publishing restriction has been lifted. You can now publish builds again.",
        "notify.unlistedTitle":       "Build Removed",
        "notify.buildUnlisted":       "Your build \"{name}\" was removed by an admin.",
        "notify.announcementTitle":   "Server Announcement",
        "toast.unknownWeapon":        "Unknown weapon in build code.",
        "toast.buildLoaded":          "Build Loaded",
        "toast.loadedSuffix":         " loaded.",
        "toast.stateRestored":        "State Restored",
        "toast.stateRestoredMsg":     "Your last build snapshot has been restored.",
        "toast.partialLoad":          "Partial Load",
        "toast.partialLoadMsg":       "{n} attachment(s) could not be found.\nGame data may have been updated.",
        "toast.importFailed":         "Import Failed",
        "toast.invalidBuildCode":     "Invalid or corrupted build code.",
        "toast.backupImportedTitle":  "Backup Imported",
        "toast.backupLoadedMsg":      "{n} build(s) loaded.",
        "toast.backupMergedMsg":      "{n} build(s) imported.",
        "toast.readFileFailed":       "Could not read backup file.",
        "toast.pasteFailed":          "Paste Failed",
        "toast.attachmentConflict":   "Attachment Conflict",
        "toast.imgGenFailed":         "Preview Generation Failed",
        "toast.imgGenFailedMsg":      "Failed to generate build preview image (502).",
        "toast.imgGenQueued":         "Preview Queued",
        "toast.imgGenQueuedMsg":      "Another user is currently generating a preview, your request is queued. This may take a moment.",
        "toast.imgGenDisabledTip":    "Build preview is temporarily unavailable. The third party image generation service is currently offline.",
        "toast.mobileWarningTitle":   "Mobile Device Detected",
        "toast.mobileWarningMsg":     "This site is optimised for desktop. For the best experience, enable \"Request Desktop Site\" in your browser or visit on a PC.",
        "toast.largeScreenTitle":     "High Resolution Detected",
        "toast.largeScreenMsg":       "This app is designed for 1080p. Hold Ctrl and scroll to scale page contents.",
        "toast.updateAvailableTitle": "Update Available",
        "toast.updateAvailableMsg":   "A newer version of EFTForge has been deployed.",
        "toast.updateNow":            "Update Now",
        "toast.devDataUpdatedTitle":  "New Data Synced",
        "toast.devDataUpdatedMsg":    "The background sync found new tarkov.dev data. Refresh to load it.",
        // Conflict reason prefixes
        "conflict.incompatibleWith":  "Is incompatible with: ",
        "conflict.slot":              "Conflicts with slot: ",
        "conflict.blockedBy":         "Blocked by installed item: ",
        // UI labels
        "ui.cancel":              "Cancel",
        "ui.overwrite":           "Overwrite",
        "ui.confirm":             "Confirm?",
        "ui.load":                "Load",
        "ui.copy":                "Copy",
        "ui.skip":                "Skip",
        "ui.rename":              "Rename",
        "ui.continue":            "Continue",
        "ui.noAmmoFound":         "No ammo found",
        "ui.noGrenade":           "- No grenade -",
        "ui.selectAttFor":        "Select Attachment for ",
        "ui.imgGen":              "Generate Previews",
        "ui.compare":             "Compare",
        "ui.favorites":           "Favorite",
        "ui.noAttachments":       "No attachments match the current filters.",
        "ui.purchasableOnly":     "Buyable",
        "ui.purchasableOnlyTip":  "Hides attachments not sold by traders at the currently set loyalty levels. Set levels in the Price tab under Set Trader Levels.",
        "ui.taskUnlock":          "Quest: ",
        "ui.compareBaseline":     "BASELINE",
        "ui.compareHintSelect":   "Click any attachment to set it as the comparison baseline",
        "ui.compareHintBaseline": "Baseline set - hover to compare, click to change baseline",
        "ui.comboList":           "List",
        "ui.graph":               "Graph",
        "ui.combo":               "Combo",
        "ui.comboLoading":           "Calculating combinations",
        "ui.comboProgress":          "Calculating {slot} for {parent} ({frontier})",
        "ui.comboProgressCapped":    "Calculating {slot} for {parent} ({frontier}/{cap}, capped)",
        "ui.comboTruncatedTitle":    "Results Truncated",
        "ui.comboTruncatedMsg":      "This attachment has too many configurations to fully evaluate. Only a subset of combinations is shown - results may not include the optimal setup.",
        "ui.comboNone":              "No combinations found for this slot",
        "ui.comboError":             "Failed to load combinations",
        "ui.comboLabel":             "COMBO",
        "ui.comboCapped":            "Showing top {count} combinations",
        // Graph view
        "graph.xLabel":              "Recoil Modifier",
        "graph.yLabel":              "EvoErgo",
        "graph.yLabelErgo":          "Ergo",
        "graph.tooltipRecoil":       "Recoil",
        "graph.tooltipEvoErgo":      "EvoErgo",
        "graph.tooltipErgo":         "Ergo",
        "graph.resetZoom":           "Reset zoom",
        "graph.hideCrosshair":       "Hide crosshair",
        "graph.showCrosshair":       "Show crosshair",
        "graph.hideLabels":          "Hide labels",
        "graph.showLabels":          "Show labels",
        "graph.switchToErgo":        "Switch to Ergo",
        "graph.switchToEvoErgo":     "Switch to EvoErgo",
        "graph.hideHints":           "Hide hints",
        "graph.showHints":           "Show hints",
        "graph.hintCycle":           "Scroll to cycle",
        "graph.hintScroll":          "Ctrl + scroll to zoom",
        "graph.hintPan":             "Middle-drag to pan",
        "graph.hintBoxZoom":         "Click and drag to box zoom",
        "graph.hintReset":           "Right click to reset",
        "graph.iconScale":           "Icon / label size",
        "graph.export":              "Export graph",
        "graph.exportTitle":         "Export Graph",
        "graph.exportDownload":      "Download PNG",
        "graph.exportGenerating":    "Generating image...",
        "graph.exportFailed":        "Export failed",
        "graph.exportStatus1":       "Loading assets...",
        "graph.exportStatus2":       "Loading {n} icons...",
        "graph.exportStatus3":       "Rendering image...",
        // Build image export
        "build.exportImg":           "Export build image",
        "build.exportTitle":         "Export Build Image",
        "build.exportGenerating":    "Generating image...",
        "build.exportFailed":        "Export failed",
        "build.exportStatus1":       "Fetching build image...",
        "build.exportStatus2":       "Loading {n} icons...",
        "build.exportStatus3":       "Rendering image...",
        // Graph custom item search
        "graph.graphProperties":     "Graph Properties",
        "graph.clearItems":          "Clear All",
        "graph.plotted":             "Plotted",
        "graph.searchPlaceholder":   "Search guns & attachments...",
        "graph.catAttachments":      "Attachments",
        "graph.filterAll":           "All",
        "graph.filterWeapons":       "Weapons",
        "graph.filterAttachments":   "Attachments",
        "graph.customGraph":         "Custom Graph",
        "graph.gunFactory":          "Factory",
        "graph.gunStripped":         "Stripped",
        "graph.xLabelVertical":      "Vertical Recoil",
        "graph.xLabelHorizontal":    "Horizontal Recoil",
        "graph.noResults":           "No results",
        // Axis config strip
        "graph.axisConfig":          "Axis Settings",
        "graph.xAxis":               "X Axis",
        "graph.yAxis":               "Y Axis",
        "graph.metricVRecoil":       "V-Recoil",
        "graph.metricHRecoil":       "H-Recoil",
        "graph.metricErgo":          "Ergo",
        "graph.metricRecoilMod":     "Recoil Mod",
        "graph.metricEvoErgo":       "EvoErgo",
        "graph.disabledMixType":     "Can't mix weapons and attachments on the same graph",
        // Weapon class display names
        "class.Assault rifle":    "Assault Rifles",
        "class.Assault carbine":  "Assault Carbines",
        "class.Marksman rifle":   "Marksman Rifles",
        "class.Sniper rifle":     "Sniper Rifles",
        "class.Machinegun":       "Light Machine Guns",
        "class.Machine gun":      "Light Machine Guns",
        "class.Machine Gun":      "Light Machine Guns",
        "class.SMG":              "Submachine Guns",
        "class.Submachine gun":   "Submachine Guns",
        "class.Shotgun":          "Shotguns",
        "class.Handgun":          "Handguns",
        "class.Revolver":         "Revolvers",
        "class.Grenade launcher": "Grenade Launchers",
        "class.Grenade Launcher": "Grenade Launchers",
        "class.Primary":          "Other",
        // Slot names (keys match the display names returned by the tarkov.dev API)
        "slot.Barrel":            "Barrel",
        "slot.Muzzle":            "Muzzle",
        "slot.Stock":             "Stock",
        "slot.Handguard":         "Handguard",
        "slot.Scope":             "Scope",
        // Attachment ratings
        "rating.like":            "Give the attachment a like!",
        "rating.dislike":         "This attachment is trash, yo",
        // Build ratings
        "cb.rating.like":         "Give this build a like!",
        "cb.likes":               "likes",
        "modal.tabMyBuilds":      "MY LOCAL BUILDS",
        "modal.tabCommunity":     "MY COMMUNITY BUILDS",
        "modal.myCommunityEmpty":   "You haven't published any community builds yet.",
        "modal.myCommunityLoading": "Loading your community builds...",
        "modal.myCommunityError":   "Could not load your community builds.",
        // Leaderboard
        "btn.leaderboard":              "Leaderboards",
        "lb.title":                     "LEADERBOARDS",
        "lb.builds":                    "Community Builds",
        "lb.attachments":               "Attachments",
        "lb.period2w":                  "Last 2 Weeks",
        "lb.periodAll":                 "All Time",
        "lb.sortLikes":                 "Most Liked",
        "lb.sortDislikes":              "Most Disliked",
        "lb.categoryAll":               "All Slots",
        "lb.buildsInfo":                "Top 10 builds from the last 2 weeks will be nominated as Featured Builds!",
        "lb.empty":                     "No entries yet.",
        "lb.loadError":                 "Could not load leaderboard.",
        "lb.top10":                     "Top 10",
        "lb.top20":                     "Top 20",
        "lb.top50":                     "Top 50",
        "lb.top100":                    "Top 100",
        "lb.likes":                     "likes",
        "lb.dislikes":                  "dislikes",
        "lb.buildLoaded":               "Build Loaded from Leaderboard",
        "lb.gunFilterAll":              "All Guns",
        // Stat tracker
        "btn.tracker":                  "Tracker",
        "tracker.title":                "STAT TRACKER",
        "tracker.lastSynced":           "Data synced {date}",
        "tracker.loading":              "Loading...",
        "tracker.loadError":            "Could not load tracker data.",
        "tracker.empty":                "Heyo! No stat change has been detected in the last 7 days, but if any hidden changes were detected, we will show what changed in here!",
        "tracker.statLabel.ergonomics_modifier": "Ergonomics",
        "tracker.statLabel.recoil_modifier":     "Recoil %",
        "tracker.statLabel.weight":              "Weight",
        "tracker.statLabel.recoil_vertical":     "Ver. Recoil",
        "tracker.statLabel.recoil_horizontal":   "Hor. Recoil",
        "tracker.statLabel.base_ergonomics":     "Base Ergo",
        "tracker.statLabel.center_of_impact":    "MOA",
        "tracker.statLabel.accuracy_modifier":   "Accuracy %",
        "tracker.statLabel.ammo_damage":         "Damage",
        "tracker.statLabel.penetration_power":   "Penetration",
        "tracker.statLabel.armor_damage":        "Armor DMG %",
        "tracker.statLabel.velocity":            "Velocity (m/s)",
        "tracker.statLabel.fragmentation_chance":"Frag Chance",
        "tracker.statLabel.heat_factor":         "Heat",
        "tracker.statLabel.cooling_factor":      "Cooling",
        "tracker.statLabel.durability_burn_factor": "Durability Burn",
        "tracker.statLabel.velocity_modifier":   "Muzzle Velocity %",
        "tracker.search.placeholder":            "Search items...",
        "tracker.filter.all":                    "All",
        "tracker.filter.weapons":                "Weapons",
        "tracker.filter.attachments":            "Attachments",
        "tracker.filter.ammo":                   "Ammo",
        "tracker.col.new":                       "NEW",
        "tracker.col.buffs":                     "BUFFS",
        "tracker.col.nerfs":                     "NERFS",
        "tracker.col.mixed":                     "MIXED",
        // Ammo table
        "btn.ammo":                   "Ballistics",
        "ammo.title":                 "AMMO & BALLISTICS",
        "ammo.loading":               "Loading ammo data...",
        "ammo.loadError":             "Could not load ammo data.",
        // Optimizer
        "optimizer.title":               "Optimizer",
        "optimizer.tabOptimize":         "Optimize",
        "optimizer.tabGunsmith":         "Gunsmith",
        "optimizer.weapon":              "Weapon",
        "optimizer.weightAdjustment":    "Weight Adjustment",
        "optimizer.resetSection":        "Reset to defaults",
        "optimizer.ergonomics":          "Ergonomics",
        "optimizer.evoErgoShort":        "EvoErgo",
        "optimizer.recoil":              "Recoil",
        "optimizer.price":               "Price",
        "optimizer.useEvoErgo":          "Use EvoErgo",
        "optimizer.presetRecoil":        "Recoil",
        "optimizer.presetErgo":          "Ergo",
        "optimizer.presetBalanced":      "Balanced",
        "optimizer.presetMinOperable":   "Min. operable",
        "optimizer.presetPerformance":   "Performance",
        "optimizer.presetRecoilFocus":   "Recoil+",
        "optimizer.presetErgoFocus":     "Ergo+",
        "optimizer.presetSaveTitle":     "Save current weights as a preset",
        "optimizer.presetNamePlaceholder": "Preset name...",
        "optimizer.presetDeleteTitle":   "Delete preset",
        "optimizer.weightUiLabel":       "Weight control",
        "optimizer.weightUiSliders":     "Sliders",
        "optimizer.weightUiTriangle":    "Triangle",
        "optimizer.on":                  "On",
        "optimizer.off":                 "Off",
        "optimizer.constraints":         "Constraints",
        "optimizer.budget":              "Budget Limit",
        "optimizer.minErgo":             "Min Ergonomics",
        "optimizer.maxWeight":           "Max Weight (kg)",
        "optimizer.minMagCapacity":      "Min Magazine Capacity",
        "optimizer.minSightingRange":    "Min Sighting Range (m)",
        "optimizer.maxSpread":           "Max MOA",
        "optimizer.roundsUnit":          "rounds",
        "optimizer.moaUnit":             "MOA",
        "optimizer.preventOverswing":    "Prevent Overswing",
        "optimizer.requireSuppressor":   "Suppressed",
        "optimizer.exactSliderFloor":    "Exact slider floor",
        "optimizer.exactSliderFloorTooltip": "When on, the slider's minimum is computed by actually solving for the best achievable MOA (slower, exact). When off, the minimum is a theoretical estimate that may not be reachable in practice.",
        "optimizer.modFilter":           "Attachment Filtering",
        "optimizer.filterByItemHint":    "By item: force (+) or ban (−) one specific mod.",
        "optimizer.searchMods":          "Search attachments...",
        "optimizer.noMatches":           "No matches",
        "optimizer.loadingMods":         "Loading attachments...",
        "optimizer.modsLoadFailed":      "Could not load attachments for this weapon.",
        "optimizer.marketAccess":        "Flea Market & Traders",
        "optimizer.fleaAvailable":       "Consider Flea Market",
        "optimizer.solve":               "GO!",
        "optimizer.solving":             "Solving...",
        "optimizer.waitingForSlot":      "Server is busy, waiting for a free solver slot...",
        "optimizer.infeasible":          "No build satisfies the current constraints.",
        "optimizer.reason.moaNotSupported":          "This weapon has no accuracy (MOA) stat to constrain.",
        "optimizer.reason.noAttachmentsAvailable":   "No attachments are available under the current filters.",
        "optimizer.reason.requiredSlotUnavailable":  "Required slot {slotName} has no available attachment under the current filters.",
        "optimizer.reason.categoryGroupUnavailable": "No available item matches required category group: {groups}.",
        "optimizer.reason.minMagCapacityUnavailable":"No available magazine with capacity >= {capacity} rounds.",
        "optimizer.reason.minSightingRangeUnavailable":"No available sight with sighting range >= {range}m.",
        "optimizer.reason.requiredItemUnavailable":  "Required item {itemId} is not available under the current filters.",
        "optimizer.reason.baseWeightExceedsLimit":   "Weapon's base weight ({baseWeight}kg) already exceeds the limit ({maxWeight}kg).",
        "optimizer.reason.suppressorUnavailable":    "No available suppressor is compatible with this weapon under the current filters.",
        "optimizer.reason.alreadySolving":           "You already have an optimization running, please wait for it to finish.",
        "optimizer.reason.serverBusy":               "Server is busy solving other requests, please try again shortly.",
        "optimizer.reason.tooManyRequests":          "Too many requests, please try again shortly.",
        "optimizer.solveFailed":         "Could not reach the optimizer. Please try again.",
        "optimizer.cancelled":           "Cancelled.",
        "optimizer.itemCount":           "Attachments",
        "optimizer.useThisBuild":        "Apply This Build",
        "optimizer.task":                "Task",
        "optimizer.loadingTasks":        "Loading Gunsmith tasks...",
        "optimizer.tasksLoadFailed":     "Could not load Gunsmith tasks.",
        "optimizer.maxRecoilSum":        "Max Combined Recoil",
        "optimizer.requiredItems":       "Required items",
        "optimizer.creditText":          "{link} by AhaiMk01",
        "optimizer.creditLinkText":      "Tarkov Weapon Mod Optimizer",
        "optimizer.reoptimize":          "Re-optimize",
        "optimizer.statusOptimal":       "Optimization Status: Optimal",
        "optimizer.statusFeasible":      "Optimization Status: Feasible (time limit reached)",
        "optimizer.resultsPlaceholder":  "Configure priorities and constraints, then hit GO! to solve for the optimal build.",
        "optimizer.loadingItems":        "Loading build...",
        "optimizer.noItems":             "This build has no attachments.",
        "optimizer.buildManifest":       "Build Manifest",
        "optimizer.lockItem":            "Lock this part (force-include, then re-optimize)",
        "optimizer.banItem":             "Ban this part (exclude, then re-optimize)",
        "optimizer.baseReceiver":        "Base Receiver",
        "optimizer.factoryPreset":       "Factory Preset",
        "optimizer.retainedFromPreset":  "Retained from Preset",
        "ammo.noResults":             "No ammo matches your search.",
        "ammo.searchPlaceholder":     "Filter ammo...",
        "ammo.disclaimer.pre":        "Effectiveness ratings reflect each round's in-game inspect screen, not the ",
        "ammo.disclaimer.link":       "official wiki's ballistics table",
        "ammo.disclaimer.post":       ", the game uses its own scale.",
        "ammo.eff.vhigh":             "V. High",
        "ammo.eff.high":              "High",
        "ammo.eff.med":               "Medium",
        "ammo.eff.low":               "Low",
        "ammo.eff.vlow":              "V. Low",
        "ammo.nav.title":             "CALIBER QUICK SELECTION",
        "ammo.calType.rifle":         "Rifle / LMG",
        "ammo.calType.pistol":        "Pistol / SMG",
        "ammo.calType.shotgun":       "Shotgun",
        "ammo.calType.special":       "Grenade / Special",
        "ammo.cat.all":               "All",
        "ammo.cat.pistol":            "Pistol Rounds",
        "ammo.cat.pdw":               "PDW Rounds",
        "ammo.cat.rifle":             "Rifle Rounds",
        "ammo.cat.shotgun":           "Shotgun Rounds",
        "ammo.cat.other":             "Other",
        "ammo.note.subsonic":         "Denotes Round is Subsonic",
        "ammo.note.tracer":           "Denotes Round is a Tracer",
        "ammo.sup.subsonic":          "Subsonic",
        "ammo.sup.tracer":            "Tracer",
        "ammo.sup.tracer.red":        "Red Tracer",
        "ammo.sup.tracer.green":      "Green Tracer",
        "ammo.sup.tracer.yellow":     "Yellow Tracer",
        "ammo.col.caliber":           "Caliber",
        "ammo.col.name":              "Name",
        "ammo.col.dmg":               "DMG",
        "ammo.col.dmgTip":            "Damage per projectile",
        "ammo.col.dmgTotal":          "Total",
        "ammo.col.pen":               "Pen",
        "ammo.col.penTip":            "Penetration power",
        "ammo.col.armorDmg":          "Armor DMG",
        "ammo.col.armorDmgTip":       "Armor damage per hit",
        "ammo.col.frag":              "Frag %",
        "ammo.col.fragTip":           "Fragmentation chance",
        "ammo.col.rico":              "Rico %",
        "ammo.col.ricoTip":           "Ricochet chance",
        "ammo.col.acc":               "Acc %",
        "ammo.col.accTip":            "Accuracy modifier",
        "ammo.col.recoil":            "Recoil",
        "ammo.col.recoilTip":         "Recoil modifier",
        "ammo.col.ltBleed":           "Lt Bleed %",
        "ammo.col.ltBleedTip":        "Light bleed chance",
        "ammo.col.hvBleed":           "Hv Bleed %",
        "ammo.col.hvBleedTip":        "Heavy bleed chance",
        "ammo.col.velocity":          "m/s",
        "ammo.col.velocityTip":       "Muzzle velocity (m/s)",
        "ammo.col.class1Tip":         "Effectiveness against Class 1 armor",
        "ammo.col.class2Tip":         "Effectiveness against Class 2 armor",
        "ammo.col.class3Tip":         "Effectiveness against Class 3 armor",
        "ammo.col.class4Tip":         "Effectiveness against Class 4 armor",
        "ammo.col.class5Tip":         "Effectiveness against Class 5 armor",
        "ammo.col.class6Tip":         "Effectiveness against Class 6 armor",
        // Slot names
        "slot.Front Sight":       "Front Sight",
        "slot.Rear Sight":        "Rear Sight",
        "slot.Pistol Grip":       "Pistol Grip",
        "slot.Magazine":          "Magazine",
        "slot.Gas Block":         "Gas Block",
        "slot.Foregrip":          "Foregrip",
        "slot.Ch. Handle":        "Charging Handle",
        "slot.Mount":             "Mount",
        "slot.Tactical":          "Tactical",
        "slot.Bipod":             "Bipod",
        "slot.Receiver":          "Receiver",
        "slot.Ubgl":              "UBGL",
        "slot.Grip":              "Grip",
        "slot.Trigger":           "Trigger",
        "slot.Hammer":            "Hammer",
        "slot.Chamber":           "Chamber",
        "slot.Catch":             "Catch",
        // Build tabs
        "tab.duplicate":          "Duplicate",
        "tab.pin":                "Pin",
        "tab.unpin":              "Unpin",
        "tab.close":              "Close",
        "tab.hintMiddleClick":    "Middle-click a tab to close it instantly",
        "tab.manyTabsTitle":      "Excessive Tabs Notice",
        "tab.manyTabsMsg":        "You have 20+ tabs open, which may have an impact on site / device performance. Consider closing any unused tabs.",
        "tab.manyTabsDismiss":    "Don't Show Again",
        // Desktop app (settings modal + local-mode prompts)
        "dt.navLabel":            "Settings",
        "dt.sectionCommunity":    "Community Features",
        "dt.modeConnected":       "Connected to EFTForge.com",
        "dt.modeConnectedDesc":   "Community builds, ratings and comments come from the live EFTForge.com service.",
        "dt.modeLocal":           "Fully local",
        "dt.modeLocalDesc":       "Community features are disabled and nothing leaves this computer (item data still syncs from tarkov.dev).",
        "dt.modeChanged":         "Mode changed - reload to apply it everywhere.",
        "dt.reloadNow":           "Reload Now",
        "dt.sectionClose":        "On Close",
        "dt.closeTray":           "Minimize to Tray",
        "dt.closeTrayDesc":       "Closing the window sends EFTForge to the system tray instead of exiting.",
        "dt.closeExit":           "Exit the App",
        "dt.closeExitDesc":       "Closing the window fully exits EFTForge.",
        "dt.closeTitle":          "Close EFTForge",
        "dt.closeBody":           "Do you want to minimize EFTForge to the system tray, or exit completely?",
        "dt.closeRemember":       "Remember my choice",
        "dt.sectionUpdates":      "App Update Source",
        "dt.updateSourceHint":    "Where the app checks for new versions. Applies on next launch.",
        "dt.srcAuto":             "Auto (Gitee first, GitHub fallback)",
        "dt.updDownloading":      "Downloading update v{v}...",
        "dt.updInstalling":       "Download complete - installing. The app will close and restart by itself.",
        "dt.updError":            "Update failed: ",
        "dt.sectionData":         "Item Data",
        "dt.lastSynced":          "Last synced from tarkov.dev: ",
        "dt.never":               "never",
        "dt.syncNow":             "Check for Item Data Updates",
        "dt.syncRunning":         "Syncing from tarkov.dev...",
        "dt.syncChanged":         "New item data installed - reload to see it.",
        "dt.syncUnchanged":       "Already up to date.",
        "dt.syncError":           "Sync failed: ",
        "dt.appVersion":          "App version: ",
        "dt.dataDir":             "Data folder: ",
        "dt.winMinimize":         "Minimize",
        "dt.winMaximize":         "Maximize",
        "dt.winRestore":          "Restore",
        "dt.winClose":            "Close",
        "stg.title":              "Settings",
        "perf.section":           "Performance",
        "perf.appMem":            "App Memory",
        "perf.appCpu":            "App CPU",
        "perf.backendMem":        "Backend Memory",
        "perf.backendCpu":        "Backend CPU",
        "perf.jsHeapUsed":        "JS Heap Used",
        "perf.jsHeapLimit":       "JS Heap Limit",
        "perf.fps":               "FPS",
        "perf.memUnsupported":    "Memory usage isn't exposed by this browser - only available in Chromium-based browsers (Chrome, Edge).",
        "perf.sysMem":            "System Memory",
        "perf.backendUptime":     "Backend Uptime",
        "perf.backendNotRunning": "not running",
        "perf.domNodes":          "DOM Nodes",
        "perf.localStorage":      "Local Storage",
        "perf.uptime":            "Session Uptime",
        "cb.localModeMsg":        "Community features are disabled in local mode. Connect to EFTForge.com live services to browse community builds, ratings and comments.",
        "cb.goOnlineBtn":         "Connect to EFTForge.com",
        "bp.localModeTip":        "Preview generation is disabled in local mode",
    },
    zh: {
        // Header
        "btn.about":            "关于",
        "btn.builds":           "配置",
        "btn.news":             "新闻",
        // News page
        "news.title":           "最新动态",
        "news.loading":         "加载中...",
        "news.loadError":       "无法加载内容，请检查网络连接。",
        "news.postNotFound":    "文章不存在。",
        "news.noPosts":         "暂无文章，敬请期待。",
        "news.backToList":      "返回动态列表",
        "ui.close":             "关闭",
        "ui.newBadge":          "新！",
        // Weapon selector toggles
        "btn.primary":          "主武器",
        "btn.pistol":           "手枪",
        "btn.caliber":          "口径",
        "btn.class":            "类型",
        // Left build area buttons
        "btn.back":             "← 返回",
        "btn.backShort":        "返回",
        "btn.resetShort":       "重置",
        "btn.stripShort":       "清除",
        "btn.saveShareShort":   "保存",
        "btn.gunBuildsShort":   "探索",
        "btn.reset":            "重置配件",
        "btn.strip":            "清除配件",
        "btn.saveShare":        "保存 / 分享",
        "btn.gunBuilds":        "探索配置",
        // Search placeholders
        "placeholder.gunSearch":  "输入搜索...",
        "placeholder.attSearch":  "输入搜索...",
        // Right panel placeholder
        "placeholder.modding":    "选择配件槽位即可开始改装...",
        "placeholder.rightClick": "右键配件可将其移除",
        "placeholder.longPress":  "向左滑动已安装的配件可将其移除",
        // Mobile tab bar
        "tab.build":               "改装",
        "tab.attachments":         "配件",
        "modal.installAttachment": "安装配件",
        "modal.weight":            "重量",
        "modal.recoil":            "后坐力 %",
        "modal.ergo":              "人机工效",
        "modal.evoErgo":           "Evo人机工效",
        "modal.cancel":            "取消",
        "modal.install":           "安装",
        "modal.remove":            "移除",
        // Stats panel
        "stats.title":              "当前配置",
        "stats.compareMode":        "对比模式",
        "stats.ergo":               "人机工效",
        "stats.verRecoil":          "垂直后坐力",
        "stats.horRecoil":          "水平后坐力",
        "stats.accuracy":           "精准度",

        "stats.weight":             "重量：",
        "stats.sightingRange":      "瞄具有效距离：",
        "stats.muzzleVelocity":     "膛口初速：",
        "stats.noAmmo":             "无弹药",
        "stats.eed":                "Evo人机Delta",
        "stats.eedLabel":           "Evo人机Delta（EED）：",
        "stats.eedLabelShort":      "EED：",
        "stats.overswing":          "过摆：",
        "stats.armStamina":         "手臂耐力",
        "stats.fullMag":            "装满弹匣",
        "stats.ammoDisabledTitle":  "选择已禁用",
        "stats.ammoDisabledTip":    "装满弹匣已关闭",
        "stats.strengthLv":         "力量等级",
        "stats.selectWeapon":       "请选择武器以开始",
        "stats.staminaDisclaimer":  "站立时手臂耐力耗尽所需秒数。\n预计偏差 ±0.5s",
        "stats.eedDesc":            "与纸面人机不同，Evo人机工效将装备重量一并纳入计算。两把Evo人机相同的枪操纵性理论上完全一致（过摆行为与开镜速度均相同，除去技能等级等变量影响）。人物重量会影响开镜速度，但不影响过摆。请设置装备人机工效修正以获得准确结果。",
        "stats.overswingDesc":      "表示开镜后准星是否会摆过中心点。当EED为负时发生。预计偏差 \u00B12 EED。",
        "stats.equipErgoLabel":     "装备人机工效修正",
        "stats.equipErgoDisclaimer":"所佩戴装备（头盔、防弹衣、背包、战术背心、面罩、护目镜）的人机工效惩罚总和 - 请根据游戏中的实际装备进行设置。",
        "stats.eedWarnTooltip":         "EED 接近过摆阈值。若您的装备降低了人机工效，此配置可能发生过摆 - 建议设置装备人机工效修正。",
        "stats.configEquipErgoTooltip": "设置装备人机工效修正",
        "stats.configStrengthTooltip":  "设置力量等级",
        "stats.yes":                "是",
        "stats.no":                 "否",
        // Advanced stats
        "hidden.showBtn":           "显示高级属性",
        "hidden.hideBtn":           "隐藏高级属性",
        "hidden.title":             "高级属性",
        "hidden.heatFactor":        "发热系数",
        "hidden.coolingFactor":     "冷却系数",
        "hidden.durabilityBurn":    "耐久损耗系数",
        "hidden.aimPlane":          "瞄准偏差",
        "hidden.aimSens":           "瞄准灵敏度",
        "hidden.camAngleStep":      "相机角度步长",
        "hidden.camSnap":           "相机回中",
        "hidden.mountCamSnap":      "架枪相机回中",
        "hidden.mountHRec":         "架枪水平后坐力",
        "hidden.mountVRec":         "架枪垂直后坐力",
        "hidden.mountBreath":       "架枪呼吸晃动",
        "hidden.devCurve":          "偏差曲线",
        "hidden.devMax":            "最大偏差",
        "hidden.recAngle":          "后坐力角度",
        "hidden.recHandRot":        "后坐手部旋转",
        "hidden.recDispersion":     "后坐力散布",
        "hidden.recReturnSpeed":    "后坐回中速度",
        "hidden.tip.aimPlane":      "开镜状态下武器的基础弹道散布",
        "hidden.tip.aimSens":       "开镜时相机对鼠标输入的响应幅度",
        "hidden.tip.camAngleStep":  "每次步进时摄像机视角的偏移量",
        "hidden.tip.camSnap":       "后坐力结束后相机回正到基准位置的速度",
        "hidden.tip.devCurve":      "随时间变化的弹道偏差曲线函数",
        "hidden.tip.devMax":        "与瞄准点的最大可能偏差",
        "hidden.tip.mountCamSnap":  "架枪状态下相机回正力度倍数",
        "hidden.tip.mountHRec":     "架枪射击时水平后坐力倍数",
        "hidden.tip.mountVRec":     "架枪射击时垂直后坐力倍数",
        "hidden.tip.mountBreath":   "架枪状态下体力耗尽时晃动幅度倍数",
        "hidden.tip.recAngle":      "后坐力模板的偏移方向角度",
        "hidden.tip.recHandRot":    "后坐力手部旋转分类倍数",
        "hidden.tip.recDispersion": "连发射击时后坐力模板的散布范围",
        "hidden.tip.recReturnSpeed":"后坐力结束后武器回正到基准位置的速度",
        "hidden.tip.heatFactor":    "当前已安装的全部配件与所选弹药的单发热量累积倍数总和",
        "hidden.tip.coolingFactor": "当前已安装的全部配件的射击间冷却速度倍数总和",
        "hidden.tip.durabilityBurn": "当前已安装的全部配件与所选弹药导致的耐久损耗倍数总和",
        "hidden.tooltip":           "标有 ? 的属性目前暂无数据（数据源尚未收录该武器）",
        // Price view
        "stats.buildCost":          "配置价格",
        "stats.pveModeLabel":       "PVE",
        "stats.totalCost":          "合计",
        "stats.ammoRow":            "弹药",
        "stats.ubglAmmoRow":        "下挂榴弹发射器弹药",
        "stats.buildView":          "配件",
        "stats.factoryIncluded":    "原厂",
        "stats.baseReceiver":       "基础机匣",
        "stats.baseFactoryPreset":  "工厂预设",
        "stats.priceView":          "价格",
        "stats.fleaMarket":         "获取跳蚤市场信息",
        "stats.fleaLabel":          "跳蚤",
        "stats.fleaTs":             "上一次跳蚤获取:",
        "stats.refetchFlea":        "刷新价格",
        "stats.refetchingFlea":     "正在获取",
        "stats.fetchingFleaPrices": "正在获取跳蚤价格",
        "stats.fleaFetching":       "正在获取",
        "stats.fleaFetchingItems":  "个物品的价格...",
        "stats.fleaCached":         "价格已缓存。",
        "stats.fleaUpdated":        "价格已更新。",
        "stats.traderLevels":       "设置商人等级",
        "stats.traderLevelsAll":    "全部",
        // Attachment tree
        "tree.title":             "工作台",
        "tree.swipeHint":         "左滑以移除配件",
        // Attachment table column headers
        "th.name":                "名称",
        "th.weight":              "重量 (kg)",
        "th.recoil":              "后坐力",
        "th.recoilList":          "后坐力修正",
        "th.recoilCombo":         "后坐力%变化",
        "th.recoilTooltipList":   "配件的游戏内后坐力修正值，与游戏内双击检视配件时显示的属性一致。",
        "th.recoilTooltipCombo":  "当前配置的实际后坐力变化百分比。\n由于其他已安装配件已降低了基础后坐力，该值通常大于配件本身的修正值。",
        "th.ergo":                "人机工效",
        "th.accuracy":            "精准度",
        "th.rubRecoil":           "₽/后坐",
        "th.rubRecoilTooltip":    "组合总价 / 后坐力。越低代表每点后坐力降低的成本越低。",
        "th.balance":             "R+E",
        "th.balanceTooltip":      "按后坐力与人机工效的综合得分排序。\n拖动滑块控制你愿意为人机工效牺牲多少后坐力。\n滑块最左 = 纯后坐力优先，最右 = 纯人机工效优先。",
        "ui.balanceRecoil":       "后坐",
        "ui.balanceErgo":         "人机",
        "th.evoErgo":             "Evo人机",
        "th.price":               "价格",
        "th.priceTooltip":        "如需切换PvP舆PvE定价，请打开价格面板并切换PvE模式",
        "th.heatCoolBurn":        "发热/冷却/耐久损耗",
        "th.muzzleVelocity":      "膛口初速",
        // Build manager modals
        "modal.save":             "保存配置",
        "modal.share":            "分享配置",
        "modal.import":           "导入配置",
        "modal.backup":           "备份",
        "modal.builds":           "已保存配置",
        "modal.exploreBuilds":    "探索配置",
        "modal.myBuilds":         "我的方案",
        "modal.communityBuilds":  "社区方案",
        "modal.publishBtn":       "发布",
        "modal.publishedBtn":     "已发布",
        "modal.unlistBtn":        "下架",
        "modal.noPublicBuilds":   "暂无社区方案，成为第一个发布的人！",
        "modal.publicBuildsError": "无法加载社区方案。",
        "modal.communityBuildsUnavailable": "社区方案功能暂时不可用，请稍后再试。",
        "modal.publishLoading":   "正在加载社区方案...",
        "modal.anonymousAuthor":  "塔科夫市民",
        "cb.featured":            "推荐",
        "cb.statWeight":          "重量",
        "cb.statOverswing":       "过摆",
        "cb.statCost":            "费用",
        "cb.statsNote":           "数据为发布时快照",
        "cb.loads":               "次加载",
        "cb.comments":            "评论",
        "cb.noComments":          "暂无评论。",
        "cb.commentsLoading":     "加载中...",
        "cb.commentsError":       "评论加载失败。",
        "cb.commentPlaceholder":  "写下评论...",
        "cb.commentSubmit":       "发送",
        "cb.commentError":        "评论发送失败。",
        "cb.deleteCommentFailed": "评论删除失败。",
        "cb.infoTooltip":         "社区方案是玩家们为这把武器分享的配装。\n\n在「保存 / 分享」中保存配装后，点击「发布」即可分享给社区。\n\n优秀的配装有机会被设为推荐方案，用心搭配，让别人看到你的杰作！\n\n查看排行榜，发现最热门及史上最高赞配装。给喜欢的配装点赞，助它登顶！",
        "cb.limitReachedTitle":   "方案数量已达上限",
        "cb.limitReachedMsg":     "该武器的社区方案数量已达到上限，请联系网站管理员处理。",
        "cb.searchPlaceholder":   "搜索方案...",
        "cb.noMatch":             "没有匹配的社区方案。",
        "cb.sort.default":        "默认",
        "cb.sort.newest":         "最新",
        "cb.sort.loads":          "最多加载",
        "cb.sort.rating":         "最高评分",
        "cb.sort.eed":            "最高Evo人机",
        "cb.sort.recoil":         "最低垂直后坐",
        "cb.sort.price":          "最低费用",
        "modal.saveName":         "配置名称...",
        "modal.saveBtn":          "保存",
        "modal.tagFilterLabel":   "标签筛选：",
        "tag.meta":               "满改",
        "tag.budget":             "性价比",
        "tag.cqb":                "CQB",
        "tag.sniper":             "远距离",
        "tag.recoil":             "低后座",
        "tag.ergo":               "高人机",
        "tag.pve":                "PvE",
        "tag.beginner":           "新手",
        "tag.hybrid":             "综合",
        "modal.copyBtn":          "复制配置码",
        "modal.copied":           "已复制！",
        "modal.pasteBtn":         "粘贴",
        "modal.importBtn":        "导入",
        "modal.exportBtn":        "导出备份",
        "modal.importFile":       "从文件导入",
        "modal.dropToImport":     "松开以导入文件",
        "modal.searchBuilds":     "按名称或武器搜索...",
        "modal.searchBuildsGun":  "按配置名称搜索...",
        "modal.noBuilds":         "暂无保存的配置。",
        "modal.publishHint":      "如需发布方案，请先保存，再点击下方的发布按钮。",
        "modal.publishHintMobile": "移动端不支持发布社区配置方案。",
        "modal.noMatch":          "未找到匹配的配置。",
        "modal.saveAndShare":     "保存 & 分享",
        "modal.pasteBuildCode":   "粘贴配置码以导入...",
        "modal.alreadyExists":    " 在此武器中已存在。",
        "modal.overwriteConfirm": "是否覆盖该配置？",
        "modal.restoreTitle":     "未完成的配置",
        "modal.restoreSubtitle":  "检测到未保存的武器配置，是否继续？",
        "modal.restoreContinue":  "继续",
        "modal.restoreAbandon":   "放弃",
        "modal.discardTitle":     "未保存的更改",
        "modal.discardSubtitle":  "您有未保存的更改。您确定要放弃更改？",
        "modal.discardConfirm":   "是",
        "modal.discardCancel":    "否",
        "modal.importBackup":     "导入备份",
        "modal.importMode":       "导入模式",
        "modal.backupInfo":       "{v} 版本中的 {n} 个配置",
        "modal.mergeBtn":         "合并到现有配置",
        "modal.overwriteAllBtn":  "覆盖全部",
        "modal.versionMismatch":  "\u26A0 版本不匹配",
        "modal.versionMismatchDesc": "此备份由版本 {version} 创建（当前版本：{current}），可能存在兼容问题。",
        "modal.areYouSure":       "确定要继续吗？",
        "modal.nameConflicts":    "名称冲突",
        "modal.conflictsDesc":    "以下配置已存在，请选择处理方式。",
        "modal.conflict":         "个冲突",
        "modal.conflicts":        "个冲突",
        "modal.confirmAll":       "全部确认",
        "modal.newBuildName":     "新配置名称...",
        "modal.nameEmpty":        "名称不能为空。",
        "modal.nameTaken":        "该名称在此武器中已存在。",
        "modal.nameDuplicate":    "此次导入中存在重复名称。",
        // Profile
        "profile.title":              "我的资料",
        "profile.username":           "显示名称",
        "profile.usernamePlaceholder":"塔科夫市民",
        "profile.usernameHint":           "将显示在您发布的配件方案与评论中。留空则保持匿名。",
        "profile.usernameInvalidChars":   "仅允许字母、数字、空格及 - _ . 符号。",
        "profile.changeAvatar":       "更换",
        "profile.save":               "保存",
        "profile.cancel":             "取消",
        "profile.saving":             "保存中...",
        "profile.savedTitle":         "档案已保存",
        "profile.savedMsg":           "您的显示名称和头像已更新。",
        "profile.avatarSelected":     "图片已就绪 - 保存时上传。",
        "profile.avatarUploading":    "正在上传头像...",
        "profile.avatarError":        "头像上传失败。",
        "profile.avatarTooLarge":     "图片大小不能超过 2 MB。",
        "profile.cropTitle":          "调整头像",
        "profile.cropHint":           "拖动调整位置 - 滚轮缩放",
        "profile.cropConfirm":        "确认",
        "profile.navLabel":           "资料",
        "profile.accountSection":     "资料",
        "profile.accountId":          "UUID",
        "profile.revealId":           "显示",
        "profile.revealWarning":      "您的 UUID 相当于密码。任何持有它的人都可以认领您的社区配置方案与评论。",
        "profile.revealConfirm":      "确认显示",
        "profile.copyId":             "复制",
        "profile.hideId":             "隐藏",
        "profile.copied":             "已复制！",
        "profile.restoreDevice":      "重绑社区数据",
        "profile.transferTitle":      "重绑社区数据",
        "profile.transferLabel":      "输入旧设备上的 UUID：",
        "profile.transferPlaceholder":"xxxxxxxx-xxxx-4xxx-xxxx-xxxxxxxxxxxx",
        "profile.transferPreview":    "预览",
        "profile.transferPreviewing": "查询中...",
        "profile.transferNoData":     "未找到该 UUID 的数据。",
        "profile.transferSelf":       "这是您当前的 UUID。",
        "profile.transferBuilds":     "条社区配置方案",
        "profile.transferComments":   "条评论",
        "profile.transferFromOld":    "来自旧资料",
        "profile.transferUnaffected": "当前资料已有，不受影响",
        "profile.transferWillTitle":  "将迁移至您目前的资料：",
        "profile.transferWontTitle":  "无法迁移（存储于旧浏览器本地）：",
        "profile.transferWont1":      "收藏的配件",
        "profile.transferWont2":      "本地保存的配置方案",
        "profile.transferAlert":      "旧设备或浏览器上的社区配置方案与评论将解除关联。",
        "profile.transferBack":       "返回",
        "profile.transferConfirm":    "确认迁移",
        "profile.transferring":       "迁移中...",
        "profile.transferDoneTitle":  "迁移完成",
        "profile.transferDoneMsg":    "条社区配置方案与评论已迁移至您的资料。",
        "profile.profileRateLimit":   "操作过于频繁，请稍后再试。",
        "profile.transferError":      "无效或无法验证的 UUID。",
        "profile.transferFailed":     "迁移失败，请稍后重试。",
        // About dialog
        "about.title":            "关于EFTForge",
        "about.reportBug":        "反馈问题",
        "about.disclaimer1":      "游戏内容及素材均为 <strong style=\"color:#bbb;\">Battlestate Games</strong> 及其授权方的商标和著作权所有。保留所有权利。",
        "about.disclaimer2":      "EFTForge是一款第三方工具，与 <strong style=\"color:#bbb;\">Battlestate Games</strong> 公司无关联，未获其认可，亦不存在任何形式的官方合作关系。",
        "about.dataSource":       "所有游戏内数据来源于",
        "about.copyright":        "\u00A9 2026 Morph1ne. 保留所有权利。",
        "about.donateShow":       "支持本项目！",
        "about.donateHide":       "隐藏收款码",
        "about.donateWechat":     "微信收款码",
        "about.donateAlipay":     "支付宝收款码",
        "about.donateDisclaimer": "100%的赞助将用于项目维护。",
        "about.checkForUpdates":  "检查更新",
        "about.checking":         "检查中...",
        "about.upToDate":         "已是最新版本。",
        "about.updateAvailable":  "有可用更新！",
        "about.updateNow":        "立即更新",
        "about.updateServerError":"无法连接服务器。",
        // Toast messages
        "toast.savedTitle":           "配置已保存",
        "toast.savedMsg":             "配置已成功保存。",
        "toast.resetTitle":           "配置已重置",
        "toast.resetMsg":             "配置已恢复到原厂状态。",
        "toast.strippedTitle":        "配件已清除",
        "toast.strippedMsg":          "所有配件已移除。",
        "toast.importedTitle":        "配置已导入",
        "toast.importedMsg":          "配置导入成功。",
        "toast.exportedTitle":        "备份已导出",
        "toast.exportedMsg":          "所有配置已导出。",
        "toast.exportedCountMsg":     "已导出 {n} 个配置。",
        "toast.noBuildsToExportTitle": "无法导出",
        "toast.noBuildsToExport":     "暂无可导出的配置。",
        "modal.deletePublishedTitle": "删除已发布配置",
        "modal.deletePublishedBody":  "该配置已发布至社区。删除本地配置将同时将其从社区列表中移除。",
        "modal.deleteAndUnlist":      "删除并下架",
        "toast.deletedTitle":         "配置已删除",
        "toast.invalidCode":          "无效的配置码。",
        "toast.invalidFile":          "无效的备份文件。",
        "toast.connectionError":      "服务器不可用",
        "toast.backendDown":          "无法加载武器列表。",
        "toast.ammoLoadFailed":       "无法加载弹药数据。",
        "toast.serverUnreachable":    "无法连接服务器。",
        "toast.attachListFailed":     "无法加载配件列表。",
        "toast.attachDataFailed":     "无法加载配件数据。",
        "toast.networkHintDev":       "请检查后端是否正在运行。",
        "toast.networkHintProd":      "服务器可能正在维护或暂时不可用。",
        "toast.syncNoticeTitle":      "每日数据同步",
        "toast.syncNoticeMsg":        "服务器将于每日 UTC+8 凌晨4:00 同步 tarkov.dev 数据。期间，网站可能无法访问（约1分钟）。",
        "toast.syncRunningTitle":     "数据同步中...",
        "toast.syncRunningMsg":       "服务器正在同步 tarkov.dev 数据，部分内容可能暂时不可用。",
        "toast.storageFull":          "存储空间已满",
        "toast.storageFullMsg":       "请删除部分已保存的配置以腾出空间。",
        "toast.saveFailed":           "保存失败",
        "toast.saveFailedMsg":        "请输入配置名称。",
        "toast.codeCopiedMsg":        "配置码已复制到剪贴板。",
        "toast.copyFailed":           "复制失败",
        "toast.clipboardFailed":      "无法访问剪贴板。",
        "toast.loadFailed":           "加载失败",
        "toast.codeCorrupted":        "配置码已损坏。",
        // Publish / unlist toasts
        "toast.publishSuccess":       "方案已发布",
        "toast.publishSuccessMsg":    "您的配件方案已向社区公开！",
        "toast.publishFailed":        "发布失败",
        "toast.publishRateLimit":     "请稍后再发布。（1分钟）",
        "toast.publishLimitReached":  "该枪械的社区配件方案已达上限，请联系网站管理员处理。",
        "toast.publishBanned":        "您已被禁止发布配件方案。",
        "toast.unlistSuccess":        "方案已下架",
        "toast.unlistSuccessMsg":     "您的配件方案已从社区移除。",
        "toast.unlistFailed":         "下架失败",
        // Publish confirm panel
        "publish.confirm":            "您即将为所有玩家发布此配件方案。",
        "publish.confirmSub":         "发布后无法修改。",
        "publish.nameWarning":        "请注意！您的自定义配置名称将会被公开，并与您的身份绑定。侮辱性、违法或滥用性名称将被管理员追溯，并承担相应后果。",
        "publish.btnCancel":          "取消",
        "publish.btnModify":          "修改",
        "publish.btnConfirm":         "确认发布",
        "publish.publishing":         "发布中...",
        "publish.mobileTray":         "查看并发布",
        "publish.slotLockedTitle":    "正在审核配置",
        "publish.slotLockedMsg":      "您正处于发布确认阶段。点击'修改'以更改配件。",
        // Admin push notifications
        "notify.bannedTitle":         "发布受限",
        "notify.banned":              "您已被临时禁止发布配件方案。封禁时长：{duration}。解封时间：{date}。",
        "notify.bannedPermanent":     "您已被永久禁止发布配件方案。",
        "notify.banReason":           "原因：{reason}",
        "notify.unbannedTitle":       "发布已恢复",
        "notify.unbanned":            "您的发布限制已解除，发布配装方案功能恢复。",
        "notify.unlistedTitle":       "方案已被移除",
        "notify.buildUnlisted":       "您的方案\"{name}\"已被管理员下架。",
        "notify.announcementTitle":   "服务器公告",
        "toast.unknownWeapon":        "配置码中包含未知武器。",
        "toast.buildLoaded":          "配置已加载",
        "toast.loadedSuffix":         " 已加载。",
        "toast.stateRestored":        "配置已恢复",
        "toast.stateRestoredMsg":     "上一次配置快照已恢复。",
        "toast.partialLoad":          "部分加载",
        "toast.partialLoadMsg":       "{n} 个配件无法找到。\n游戏数据可能已更新。",
        "toast.importFailed":         "导入失败",
        "toast.invalidBuildCode":     "无效或已损坏的配置码。",
        "toast.backupImportedTitle":  "备份已导入",
        "toast.backupLoadedMsg":      "已加载 {n} 个配置。",
        "toast.backupMergedMsg":      "已导入 {n} 个配置。",
        "toast.readFileFailed":       "无法读取备份文件。",
        "toast.pasteFailed":          "粘贴失败",
        "toast.attachmentConflict":   "配件冲突",
        "toast.imgGenFailed":         "预览图生成失败",
        "toast.imgGenFailedMsg":      "配置预览图生成失败 (502)。",
        "toast.imgGenQueued":         "预览生成中",
        "toast.imgGenQueuedMsg":      "当前有其他用户正在生成预览图，您的请求已进入队列，请稍候。",
        "toast.imgGenDisabledTip":    "预览图生成功能暂时不可用。第三方图片生成服务当前离线。",
        "toast.mobileWarningTitle":   "检测到移动设备",
        "toast.mobileWarningMsg":     "本站针对桌面端优化。如需最佳体验，请使用电脑访问。",
        "toast.largeScreenTitle":     "检测到高分辨率",
        "toast.largeScreenMsg":       "本站针对 1080p 分辨率优化，可使用 Ctrl+滚轮 以缩放界面。",
        "toast.updateAvailableTitle": "有可用更新",
        "toast.updateAvailableMsg":   "EFTForge 已发布新版本。",
        "toast.devDataUpdatedTitle":  "数据已同步",
        "toast.devDataUpdatedMsg":    "后台同步发现了新的 tarkov.dev 数据，请刷新以加载。",
        "toast.updateNow":            "立即更新",
        // Conflict reason prefixes
        "conflict.incompatibleWith":  "与以下配件冲突：",   
        "conflict.slot":              "配件冲突：",
        "conflict.blockedBy":         "被已安装配件阻止：",
        // UI labels
        "ui.cancel":              "取消",
        "ui.overwrite":           "覆盖",
        "ui.confirm":             "确认？",
        "ui.load":                "加载",
        "ui.copy":                "复制",
        "ui.skip":                "跳过",
        "ui.rename":              "重命名",
        "ui.continue":            "继续",
        "ui.noAmmoFound":         "未找到弹药",
        "ui.noGrenade":           "- 不装填榴弹 -",
        "ui.selectAttFor":        "选择配件：",
        "ui.imgGen":              "生成预览图",
        "ui.compare":             "对比",
        "ui.favorites":           "收藏",
        "ui.noAttachments":       "没有配件符合当前筛选条件。",
        "ui.purchasableOnly":     "可购",
        "ui.purchasableOnlyTip":  "隐藏当前商人等级无法购买的配件。在价格页面的「设置商人等级」中调整等级。",
        "ui.taskUnlock":          "任务解锁：",
        "ui.compareBaseline":     "基准",
        "ui.compareHintSelect":   "点击任意配件将其设为对比基准",
        "ui.compareHintBaseline": "已设置基准 - 悬停对比，点击更换基准",
        "ui.comboList":           "列表",
        "ui.graph":               "图表",
        "ui.combo":               "组合",
        "ui.comboLoading":           "正在计算组合",
        "ui.comboProgress":          "正在计算 {parent} 的 {slot} 组合 ({frontier})",
        "ui.comboProgressCapped":    "正在计算 {parent} 的 {slot} 组合 ({frontier}/{cap}, 已达上限)",
        "ui.comboTruncatedTitle":    "结果已截断",
        "ui.comboTruncatedMsg":      "该配件配置过多，无法完整评估。仅显示部分组合 - 结果可能不含最优方案。",
        "ui.comboNone":              "此槽位无可用组合",
        "ui.comboError":             "组合加载失败",
        "ui.comboLabel":             "组合",
        "ui.comboCapped":            "已显示最多 {count} 个组合",
        // Graph view
        "graph.xLabel":              "后坐力",
        "graph.yLabel":              "Evo人机工效",
        "graph.yLabelErgo":          "人机工效",
        "graph.tooltipRecoil":       "后坐力",
        "graph.tooltipEvoErgo":      "Evo人机",
        "graph.tooltipErgo":         "人机",
        "graph.resetZoom":           "重置缩放",
        "graph.hideCrosshair":       "隐藏准线",
        "graph.showCrosshair":       "显示准线",
        "graph.hideLabels":          "隐藏标签",
        "graph.showLabels":          "显示标签",
        "graph.switchToErgo":        "切换至人机",
        "graph.switchToEvoErgo":     "切换至Evo人机",
        "graph.hideHints":           "隐藏提示",
        "graph.showHints":           "显示提示",
        "graph.hintCycle":           "滚轮以切换",
        "graph.hintScroll":          "Ctrl + 滚轮以缩放",
        "graph.hintPan":             "中键拖动以平移",
        "graph.hintBoxZoom":         "左键拖动以框选缩放",
        "graph.hintReset":           "右键以重置缩放",
        "graph.iconScale":           "图标/标签大小",
        "graph.export":              "导出图表",
        "graph.exportTitle":         "导出图表",
        "graph.exportDownload":      "下载 PNG",
        "graph.exportGenerating":    "生成中...",
        "graph.exportFailed":        "导出失败",
        "graph.exportStatus1":       "正在加载资源...",
        "graph.exportStatus2":       "正在加载 {n} 个图标...",
        "graph.exportStatus3":       "正在渲染图像...",
        // Build image export
        "build.exportImg":           "导出配件方案图",
        "build.exportTitle":         "导出配件方案图",
        "build.exportGenerating":    "生成中...",
        "build.exportFailed":        "导出失败",
        "build.exportStatus1":       "正在生成武器图像...",
        "build.exportStatus2":       "正在加载 {n} 个图标...",
        "build.exportStatus3":       "正在渲染图像...",
        // Graph custom item search
        "graph.graphProperties":     "图表设置",
        "graph.clearItems":          "全部清空",
        "graph.plotted":             "图中项目",
        "graph.searchPlaceholder":   "搜索枪械与配件...",
        "graph.catAttachments":      "配件",
        "graph.filterAll":           "全部",
        "graph.filterWeapons":       "枪械",
        "graph.filterAttachments":   "配件",
        "graph.customGraph":         "自定义图表",
        "graph.gunFactory":          "原厂",
        "graph.gunStripped":         "裸枪",
        "graph.xLabelVertical":      "垂直后坐力",
        "graph.xLabelHorizontal":    "水平后坐力",
        "graph.noResults":           "无结果",
        // Axis config strip
        "graph.axisConfig":          "坐标轴设置",
        "graph.xAxis":               "X 轴",
        "graph.yAxis":               "Y 轴",
        "graph.metricVRecoil":       "垂直后坐",
        "graph.metricHRecoil":       "水平后坐",
        "graph.metricErgo":          "人机工效",
        "graph.metricRecoilMod":     "后坐力修正",
        "graph.metricEvoErgo":       "Evo人机",
        "graph.disabledMixType":     "不能在同一图表中混合枪械舆配件",
        // Weapon class display names
        "class.Assault rifle":    "突击步枪",
        "class.Assault carbine":  "突击卡宾枪",
        "class.Marksman rifle":   "精确射手步枪",
        "class.Sniper rifle":     "狙击步枪",
        "class.Machinegun":       "轻机枪",
        "class.Machine gun":      "轻机枪",
        "class.Machine Gun":      "轻机枪",
        "class.SMG":              "冲锋枪",
        "class.Submachine gun":   "冲锋枪",
        "class.Shotgun":          "霰弹枪",
        "class.Handgun":          "手枪",
        "class.Revolver":         "左轮手枪",
        "class.Grenade launcher": "榴弹发射器",
        "class.Grenade Launcher": "榴弹发射器",
        "class.Primary":          "其他",
        // Slot names (keys match the display names returned by the tarkov.dev API)
        "slot.Barrel":            "枪管",
        "slot.Muzzle":            "枪口",
        "slot.Stock":             "枪托",
        "slot.Handguard":         "护木",
        "slot.Scope":             "瞄具",
        "slot.Front Sight":       "准星",
        "slot.Rear Sight":        "照门",
        "slot.Pistol Grip":       "手枪握把",
        "slot.Magazine":          "弹匣",
        "slot.Gas Block":         "导气管",
        "slot.Foregrip":          "前握把",
        "slot.Ch. Handle":        "拉机柄",
        "slot.Mount":             "导轨",
        "slot.Tactical":          "战术配件",
        "slot.Bipod":             "脚架",
        "slot.Receiver":          "上机匣",
        "slot.Ubgl":              "下挂榴弹发射器",
        "slot.Grip":              "握把",
        "slot.Trigger":           "扳机",
        "slot.Hammer":            "击锤",
        "slot.Chamber":           "弹膛",
        "slot.Catch":             "空仓挂机柄",
        // Attachment ratings
        "rating.like":            "这个配件真好用！",
        "rating.dislike":         "这个配件真垃圾！",
        // Build ratings
        "cb.rating.like":         "这个配置真好用！",
        "cb.likes":               "点赞",
        "modal.tabMyBuilds":      "我的本地方案",
        "modal.tabCommunity":     "我的社区方案",
        "modal.myCommunityEmpty":   "你还没有发布任何社区方案。",
        "modal.myCommunityLoading": "正在加载你的社区方案...",
        "modal.myCommunityError":   "无法加载你的社区方案。",
        // Leaderboard
        "btn.leaderboard":              "排行榜",
        "lb.title":                     "排行榜",
        "lb.builds":                    "社区方案",
        "lb.attachments":               "配件",
        "lb.period2w":                  "近两周",
        "lb.periodAll":                 "全部",
        "lb.sortLikes":                 "最多点赞",
        "lb.sortDislikes":              "最多踩",
        "lb.categoryAll":               "全部槽位",
        "lb.buildsInfo":                "近两周排名前10的配置可被提名为推荐配置！",
        "lb.empty":                     "暂无数据。",
        "lb.loadError":                 "无法加载排行榜。",
        "lb.top10":                     "前10名",
        "lb.top20":                     "前20名",
        "lb.top50":                     "前50名",
        "lb.top100":                    "前100名",
        "lb.likes":                     "赞",
        "lb.dislikes":                  "踩",
        "lb.buildLoaded":               "已从排行榜加载配置",
        "lb.gunFilterAll":              "全部枪械",
        // Stat tracker
        "btn.tracker":                  "数据变动",
        "tracker.title":                "数据变动追踪",
        "tracker.lastSynced":           "数据同步于 {date}",
        "tracker.loading":              "加载中...",
        "tracker.loadError":            "无法加载追踪数据。",
        "tracker.empty":                "过去7天暂无数据变动记录，如果网站检测到某枪械/配件属性被暗改，会把改动展示在这里哦！",
        "tracker.statLabel.ergonomics_modifier": "人机工效",
        "tracker.statLabel.recoil_modifier":     "后坐力%",
        "tracker.statLabel.weight":              "重量",
        "tracker.statLabel.recoil_vertical":     "垂直后坐力",
        "tracker.statLabel.recoil_horizontal":   "水平后坐力",
        "tracker.statLabel.base_ergonomics":     "人机工效",
        "tracker.statLabel.center_of_impact":    "MOA",
        "tracker.statLabel.accuracy_modifier":   "精准度%",
        "tracker.statLabel.ammo_damage":         "伤害",
        "tracker.statLabel.penetration_power":   "穿透力",
        "tracker.statLabel.armor_damage":        "护甲损伤%",
        "tracker.statLabel.velocity":            "膛口初速 (m/s)",
        "tracker.statLabel.fragmentation_chance":"破碎概率",
        "tracker.statLabel.heat_factor":         "发热",
        "tracker.statLabel.cooling_factor":      "冷却",
        "tracker.statLabel.durability_burn_factor": "耐久损耗",
        "tracker.statLabel.velocity_modifier":   "膛口初速%",
        "tracker.search.placeholder":            "搜索物品...",
        "tracker.filter.all":                    "全部",
        "tracker.filter.weapons":                "武器",
        "tracker.filter.attachments":            "配件",
        "tracker.filter.ammo":                   "弹药",
        "tracker.col.new":                       "新增",
        "tracker.col.buffs":                     "增强",
        "tracker.col.nerfs":                     "削弱",
        "tracker.col.mixed":                     "混合",
        // Ammo table
        "btn.ammo":                   "弹药",
        "ammo.title":                 "弹药数据",
        "ammo.loading":               "加载弹药数据...",
        "ammo.loadError":             "无法加载弹药数据。",
        // Optimizer
        "optimizer.title":               "优化器",
        "optimizer.tabOptimize":         "配置优化",
        "optimizer.tabGunsmith":         "枪匠任务",
        "optimizer.weapon":              "武器",
        "optimizer.weightAdjustment":    "属性权重",
        "optimizer.resetSection":        "重置为默认值",
        "optimizer.ergonomics":          "人机工效",
        "optimizer.evoErgoShort":        "Evo人机工效",
        "optimizer.recoil":              "后坐力",
        "optimizer.price":               "价格",
        "optimizer.useEvoErgo":          "使用Evo人机工效",
        "optimizer.presetRecoil":        "纯后坐",
        "optimizer.presetErgo":          "纯人机",
        "optimizer.presetBalanced":      "性价比",
        "optimizer.presetMinOperable":   "最低可用",
        "optimizer.presetPerformance":   "均衡性能",
        "optimizer.presetRecoilFocus":   "后坐优先",
        "optimizer.presetErgoFocus":     "人机优先",
        "optimizer.presetSaveTitle":     "将当前权重保存为预设",
        "optimizer.presetNamePlaceholder": "预设名称...",
        "optimizer.presetDeleteTitle":   "删除预设",
        "optimizer.weightUiLabel":       "权重调节",
        "optimizer.weightUiSliders":     "滑动条",
        "optimizer.weightUiTriangle":    "三角形",
        "optimizer.on":                  "开",
        "optimizer.off":                 "关",
        "optimizer.constraints":         "约束条件",
        "optimizer.budget":              "预算上限",
        "optimizer.minErgo":             "最低人机工效",
        "optimizer.maxWeight":           "最大重量 (kg)",
        "optimizer.minMagCapacity":      "最低弹匣容量",
        "optimizer.minSightingRange":    "最低瞄准距离 (m)",
        "optimizer.maxSpread":           "最大MOA",
        "optimizer.roundsUnit":          "发",
        "optimizer.moaUnit":             "MOA",
        "optimizer.preventOverswing":    "防止过摆",
        "optimizer.requireSuppressor":   "消音器",
        "optimizer.exactSliderFloor":    "精确下限",
        "optimizer.exactSliderFloorTooltip": "开启时，滑块最小值由求解器实际求解得出（较慢但精确）。关闭时，最小值为理论估算，可能实际无法达到。",
        "optimizer.modFilter":           "配件过滤",
        "optimizer.filterByItemHint":    "按单品：指定某个配件必选（+）或禁用（−）。",
        "optimizer.searchMods":          "搜索具体配件…",
        "optimizer.noMatches":           "无匹配结果",
        "optimizer.loadingMods":         "正在加载配件...",
        "optimizer.modsLoadFailed":      "无法加载该武器的配件列表。",
        "optimizer.marketAccess":        "跳蚤市场与商人",
        "optimizer.fleaAvailable":       "考虑跳蚤市场",
        "optimizer.solve":               "GO!",
        "optimizer.solving":             "求解中...",
        "optimizer.waitingForSlot":      "服务器繁忙，正在等待可用的求解资源...",
        "optimizer.infeasible":          "没有配置满足当前的约束条件。",
        "optimizer.reason.moaNotSupported":          "该武器没有可供约束的精度（MOA）属性。",
        "optimizer.reason.noAttachmentsAvailable":   "当前筛选条件下没有可用的配件。",
        "optimizer.reason.requiredSlotUnavailable":  "当前筛选条件下，必需槽位 {slotName} 没有可用配件。",
        "optimizer.reason.categoryGroupUnavailable": "没有配件符合所需的分类组：{groups}。",
        "optimizer.reason.minMagCapacityUnavailable":"没有容量 ≥ {capacity} 发的可用弹匣。",
        "optimizer.reason.minSightingRangeUnavailable":"没有瞄准范围 ≥ {range}m 的可用瞄具。",
        "optimizer.reason.requiredItemUnavailable":  "所需配件 {itemId} 在当前筛选条件下不可用。",
        "optimizer.reason.baseWeightExceedsLimit":   "武器基础重量（{baseWeight}kg）已超过限制（{maxWeight}kg）。",
        "optimizer.reason.suppressorUnavailable":    "当前筛选条件下没有适配该武器的消音器。",
        "optimizer.reason.alreadySolving":           "您已有一个正在进行的优化求解，请等待其完成。",
        "optimizer.reason.serverBusy":               "服务器正忙于处理其他求解请求，请稍后重试。",
        "optimizer.reason.tooManyRequests":          "请求过于频繁，请稍后再试。",
        "optimizer.solveFailed":         "无法连接到优化器，请重试。",
        "optimizer.cancelled":           "已取消。",
        "optimizer.itemCount":           "配件数量",
        "optimizer.useThisBuild":        "应用此配置",
        "optimizer.task":                "任务",
        "optimizer.loadingTasks":        "正在加载枪匠任务...",
        "optimizer.tasksLoadFailed":     "无法加载枪匠任务。",
        "optimizer.maxRecoilSum":        "最大总后坐力",
        "optimizer.requiredItems":       "需要的配件",
        "optimizer.creditText":          "{link} - AhaiMk01",
        "optimizer.creditLinkText":      "塔科夫改枪优化器",
        "optimizer.reoptimize":          "重新优化",
        "optimizer.statusOptimal":       "优化状态：最优",
        "optimizer.statusFeasible":      "优化状态：可行（已达到时间上限）",
        "optimizer.resultsPlaceholder":  "设置好属性权重与约束后，点击 GO! 即可开始求解最优改装方案。",
        "optimizer.loadingItems":        "加载改装方案中...",
        "optimizer.noItems":             "该方案没有配件。",
        "optimizer.buildManifest":       "配件清单",
        "optimizer.lockItem":            "锁定该配件（强制包含后重新优化）",
        "optimizer.banItem":             "禁用该配件（排除后重新优化）",
        "optimizer.baseReceiver":        "基础机匣",
        "optimizer.factoryPreset":       "工厂预设",
        "optimizer.retainedFromPreset":  "预设保留配件",
        "ammo.noResults":             "没有匹配的弹药。",
        "ammo.searchPlaceholder":     "筛选弹药...",
        "ammo.disclaimer.pre":        "护甲效能评级与游戏内各弹药检视界面显示一致，与",
        "ammo.disclaimer.link":       "官方Wiki弹药数据表",
        "ammo.disclaimer.post":       "显示有所不同，游戏采用其自身的评级标准。",
        "ammo.eff.vhigh":             "很高",
        "ammo.eff.high":              "高",
        "ammo.eff.med":               "中",
        "ammo.eff.low":               "低",
        "ammo.eff.vlow":              "很低",
        "ammo.nav.title":             "口径快速选择",
        "ammo.calType.rifle":         "步枪 / 机枪",
        "ammo.calType.pistol":        "手枪 / 冲锋枪",
        "ammo.calType.shotgun":       "霰弹枪",
        "ammo.calType.special":       "榴弹 / 特殊",
        "ammo.cat.all":               "全部",
        "ammo.cat.pistol":            "手枪弹",
        "ammo.cat.pdw":               "PDW弹",
        "ammo.cat.rifle":             "步枪弹",
        "ammo.cat.shotgun":           "霰弹",
        "ammo.cat.other":             "其他",
        "ammo.note.subsonic":         "亚音速弹药",
        "ammo.note.tracer":           "曳光弹",
        "ammo.sup.subsonic":          "亚音速",
        "ammo.sup.tracer":            "曳光弹",
        "ammo.sup.tracer.red":        "红色曳光弹",
        "ammo.sup.tracer.green":      "绿色曳光弹",
        "ammo.sup.tracer.yellow":     "黄色曳光弹",
        "ammo.col.caliber":           "口径",
        "ammo.col.name":              "名称",
        "ammo.col.dmg":               "伤害",
        "ammo.col.dmgTip":            "每发弹体伤害",
        "ammo.col.dmgTotal":          "总伤害",
        "ammo.col.pen":               "穿透",
        "ammo.col.penTip":            "穿透力",
        "ammo.col.armorDmg":          "护甲伤害",
        "ammo.col.armorDmgTip":       "每次命中护甲的耐久损耗",
        "ammo.col.frag":              "碎弹%",
        "ammo.col.fragTip":           "弹药碎片化概率",
        "ammo.col.rico":              "跳弹%",
        "ammo.col.ricoTip":           "跳弹概率",
        "ammo.col.acc":               "精度%",
        "ammo.col.accTip":            "精度修正",
        "ammo.col.recoil":            "后坐力",
        "ammo.col.recoilTip":         "后坐力修正",
        "ammo.col.ltBleed":           "轻微出血%",
        "ammo.col.ltBleedTip":        "轻微出血概率",
        "ammo.col.hvBleed":           "重度出血%",
        "ammo.col.hvBleedTip":        "重度出血概率",
        "ammo.col.velocity":          "m/s",
        "ammo.col.velocityTip":       "子弹初速 (m/s)",
        "ammo.col.class1Tip":         "对1级护甲的效能",
        "ammo.col.class2Tip":         "对2级护甲的效能",
        "ammo.col.class3Tip":         "对3级护甲的效能",
        "ammo.col.class4Tip":         "对4级护甲的效能",
        "ammo.col.class5Tip":         "对5级护甲的效能",
        "ammo.col.class6Tip":         "对6级护甲的效能",
        // Build tabs
        "tab.duplicate":          "克隆",
        "tab.pin":                "置顶",
        "tab.unpin":              "取消置顶",
        "tab.close":              "关闭",
        "tab.hintMiddleClick":    "按下鼠标中键以快速关闭配置标签",
        "tab.manyTabsTitle":      "配置标签过多",
        "tab.manyTabsMsg":        "您已打开超过20个配置标签，可能会影响页面/设备性能，建议关闭不需要的配置标签。",
        "tab.manyTabsDismiss":    "不再提示",
        // Desktop app (settings modal + local-mode prompts)
        "dt.navLabel":            "设置",
        "dt.sectionCommunity":    "社区功能",
        "dt.modeConnected":       "连接 EFTForge.com",
        "dt.modeConnectedDesc":   "社区配装、评分和评论均来自 EFTForge.com 线上服务。",
        "dt.modeLocal":           "本地模式",
        "dt.modeLocalDesc":       "社区功能停用，任何数据都不会离开本地（物品数据仍从 tarkov.dev 同步）。",
        "dt.modeChanged":         "模式已切换，重新加载后全面生效。",
        "dt.reloadNow":           "立即重新加载",
        "dt.sectionClose":        "关闭时",
        "dt.closeTray":           "最小化到托盘",
        "dt.closeTrayDesc":       "关闭窗口时将 EFTForge 最小化到系统托盘，而不是退出。",
        "dt.closeExit":           "退出应用",
        "dt.closeExitDesc":       "关闭窗口时完全退出 EFTForge。",
        "dt.closeTitle":          "关闭 EFTForge",
        "dt.closeBody":           "要将 EFTForge 最小化到系统托盘，还是完全退出？",
        "dt.closeRemember":       "记住我的选择",
        "dt.sectionUpdates":      "应用更新源",
        "dt.updateSourceHint":    "应用检查新版本的渠道，下次启动时生效。",
        "dt.srcAuto":             "自动（优先 Gitee，GitHub 备用）",
        "dt.updDownloading":      "正在下载新版本 v{v}...",
        "dt.updInstalling":       "下载完成，正在安装。应用将自动关闭并重启。",
        "dt.updError":            "更新失败：",
        "dt.sectionData":         "物品数据",
        "dt.lastSynced":          "上次从 tarkov.dev 同步：",
        "dt.never":               "从未",
        "dt.syncNow":             "检查物品数据更新",
        "dt.syncRunning":         "正在从 tarkov.dev 同步...",
        "dt.syncChanged":         "已安装新的物品数据，重新加载后可见。",
        "dt.syncUnchanged":       "已是最新数据。",
        "dt.syncError":           "同步失败：",
        "dt.appVersion":          "应用版本：",
        "dt.dataDir":             "数据目录：",
        "dt.winMinimize":         "最小化",
        "dt.winMaximize":         "最大化",
        "dt.winRestore":          "还原",
        "dt.winClose":            "关闭",
        "stg.title":              "设置",
        "perf.section":           "性能",
        "perf.appMem":            "应用内存",
        "perf.appCpu":            "应用 CPU",
        "perf.backendMem":        "后端内存",
        "perf.backendCpu":        "后端 CPU",
        "perf.jsHeapUsed":        "JS 堆内存占用",
        "perf.jsHeapLimit":       "JS 堆内存上限",
        "perf.fps":               "帧率",
        "perf.memUnsupported":    "此浏览器不支持内存占用查询，仅 Chromium 内核浏览器（Chrome、Edge）支持。",
        "perf.sysMem":            "系统内存",
        "perf.backendUptime":     "后端运行时长",
        "perf.backendNotRunning": "未运行",
        "perf.domNodes":          "DOM 节点数",
        "perf.localStorage":      "本地存储占用",
        "perf.uptime":            "会话时长",
        "cb.localModeMsg":        "本地模式下社区功能不可用。连接 EFTForge.com 线上服务即可浏览社区配置、评分和评论。",
        "cb.goOnlineBtn":         "连接 EFTForge.com",
        "bp.localModeTip":        "本地模式下预览图生成服务不可用",
    },
};

function t(key) {
    const lang = (window.EFTForge.state && window.EFTForge.state.lang) || "en";
    const table = _TRANSLATIONS[lang] || _TRANSLATIONS["en"];
    return (table[key] !== undefined) ? table[key] : ((_TRANSLATIONS["en"][key] !== undefined) ? _TRANSLATIONS["en"][key] : key);
}

function tFmt(key, vars) {
    let str = t(key);
    for (const [k, v] of Object.entries(vars)) {
        str = str.replaceAll(`{${k}}`, String(v));
    }
    return str;
}

function tSlot(rawSlotName) {
    const translated = t(`slot.${rawSlotName}`);
    if (translated === `slot.${rawSlotName}`) return rawSlotName;
    return translated;
}

function tClass(rawClassName) {
    const translated = t(`class.${rawClassName}`);
    if (translated === `class.${rawClassName}`) return rawClassName;
    return translated;
}

window.EFTForge.lang = { t, tFmt, tSlot, tClass };

// Expose as globals so template literals in rendering modules can call them directly
window.t      = t;
window.tFmt   = tFmt;
window.tSlot  = tSlot;
window.tClass = tClass;
