window.EFTForge = window.EFTForge || {};

const _TRANSLATIONS = {
    en: {
        // Header
        "btn.about":            "About",
        "btn.builds":           "Builds",
        "btn.news":             "News",
        // News page
        "news.title":           "NEWS",
        "news.loading":         "Loading...",
        "news.loadError":       "Could not load content. Please check your connection.",
        "news.postNotFound":    "Post not found.",
        "news.noPosts":         "No posts yet. Check back soon.",
        "news.backToList":      "Back to News",
        "ui.close":             "Close",
        // Weapon selector toggles
        "btn.primary":          "Primary",
        "btn.pistol":           "Pistol",
        "btn.caliber":          "Caliber",
        "btn.class":            "Class",
        // Left build area buttons
        "btn.back":             "\u2190 Back",
        "btn.reset":            "Reset Build",
        "btn.strip":            "Strip Build",
        "btn.saveShare":        "Save / Share",
        "btn.gunBuilds":        "Load Build",
        // Search placeholders
        "placeholder.gunSearch":  "Start typing to search...",
        "placeholder.attSearch":  "Start typing to search...",
        // Right panel placeholder
        "placeholder.modding":    "Select an attachment slot to begin modding...",
        "placeholder.rightClick": "Right click an attachment to remove it",
        "placeholder.longPress":  "Long press an installed attachment to remove it",
        // Mobile tab bar
        "tab.build":               "Build",
        "tab.attachments":         "Attachments",
        "modal.installAttachment": "Install Attachment",
        "modal.weight":            "WEIGHT",
        "modal.recoil":            "RECOIL %",
        "modal.ergo":              "ERGONOMICS",
        "modal.evoErgo":           "EVO ERGO",
        "modal.cancel":            "Cancel",
        "modal.install":           "Install",
        "modal.remove":            "Remove",
        // Stats panel
        "stats.title":              "CURRENT BUILD",
        "stats.ergo":               "Ergonomics",
        "stats.verRecoil":          "Ver. Recoil",
        "stats.horRecoil":          "Hor. Recoil",
        "stats.weight":             "Weight:",
        "stats.eed":                "EvoErgoDelta",
        "stats.eedLabel":           "EED:",
        "stats.overswing":          "OverSwing:",
        "stats.armStamina":         "Arm Stamina",
        "stats.fullMag":            "Assume Full Magazine",
        "stats.strengthLv":         "Strength Level",
        "stats.selectWeapon":       "Select a weapon to begin",
        "stats.beta":               "BETA",
        "stats.staminaDisclaimer":  "Seconds until arm stamina depletes while standing.\nExpected deviation \u00B10.5s",
        "stats.eedDesc":            "How far your build is from the overswing threshold at EED = 0, higher is better. Two builds with the same EED behave identically for overswing; being overweight affects ADS speed but not overswing.",
        "stats.overswingDesc":      "Whether the gun will swing over the center point of aiming after ADS. Occurs when EED is negative. Estimated inaccuracy of \u00B12 EED.",
        "stats.equipErgoLabel":     "Equipment Ergonomics Modifier",
        "stats.equipErgoDisclaimer":"The total Ergonomics penalty from worn equipment (headgear, armor, backpack, rig, facecover, eyewear) - set this to match your in-game gear.",
        "stats.eedWarnTooltip":     "EED is close to the overswing threshold. If your equipment reduces ergonomics, this build may overswing - consider setting your Equipment Ergonomics Modifier.",
        "stats.yes":                "YES",
        "stats.no":                 "NO",
        // Attachment tree
        "tree.title":             "ATTACHMENT TREE",
        // Attachment table column headers
        "th.name":                "Name",
        "th.weight":              "Weight (kg)",
        "th.recoil":              "Recoil",
        "th.ergo":                "Ergonomics",
        "th.evoErgo":             "EvoErgo",
        // Build manager modals
        "modal.save":             "SAVE BUILD",
        "modal.share":            "SHARE BUILD",
        "modal.import":           "IMPORT BUILD",
        "modal.backup":           "BACKUP",
        "modal.builds":           "SAVED BUILDS",
        "modal.saveName":         "Build name...",
        "modal.saveBtn":          "Save",
        "modal.copyBtn":          "Copy Share Code",
        "modal.copied":           "Copied!",
        "modal.pasteBtn":         "Paste",
        "modal.importBtn":        "Import",
        "modal.exportBtn":        "Export Backup",
        "modal.importFile":       "Import from File",
        "modal.dropToImport":     "Drop file to import",
        "modal.searchBuilds":     "Search by build name or weapon...",
        "modal.searchBuildsGun":  "Search by build name...",
        "modal.noBuilds":         "No saved builds yet.",
        "modal.noMatch":          "No builds match your search.",
        "modal.saveAndShare":     "SAVE & SHARE",
        "modal.pasteBuildCode":   "Paste build code to import...",
        "modal.alreadyExists":    " already exists for this weapon.",
        "modal.overwriteConfirm": "Do you want to overwrite it?",
        "modal.importBackup":     "IMPORT BACKUP",
        "modal.importMode":       "IMPORT MODE",
        "modal.backupInfo":       "{n} build(s) from version {v}",
        "modal.mergeBtn":         "Merge into Existing",
        "modal.overwriteAllBtn":  "Overwrite All",
        "modal.versionMismatch":  "\u26A0 Version Mismatch",
        "modal.versionMismatchDesc": "This backup was created with {version} (current: {current}). It may cause issues.",
        "modal.areYouSure":       "ARE YOU SURE?",
        "modal.nameConflicts":    "NAME CONFLICTS",
        "modal.conflictsDesc":    "These builds already exist. Choose how to handle each one.",
        "modal.conflict":         "conflict",
        "modal.conflicts":        "conflicts",
        "modal.confirmAll":       "Confirm All",
        "modal.newBuildName":     "New build name...",
        "modal.nameEmpty":        "Name cannot be empty.",
        "modal.nameTaken":        "That name already exists for this weapon.",
        "modal.nameDuplicate":    "Duplicate rename within this import.",
        // About dialog
        "about.title":            "ABOUT EFTForge",
        "about.reportBug":        "Report Bug",
        "about.disclaimer1":      "Game content and materials are trademarks and copyrights of <strong style=\"color:#bbb;\">Battlestate Games</strong> and its licensors. All rights reserved.",
        "about.disclaimer2":      "EFTForge is an unofficial fan-made tool and is not affiliated with, endorsed by, or in any way officially connected with Battlestate Games.",
        "about.dataSource":       "All in-game data is sourced from the",
        "about.copyright":        "\u00A9 2026 Morph1ne. All Rights Reserved.",
        // Toast messages
        "toast.savedTitle":           "Build Saved",
        "toast.savedMsg":             "Your build has been saved.",
        "toast.resetTitle":           "Build Reset",
        "toast.resetMsg":             "Build has been reset to factory.",
        "toast.strippedTitle":        "Build Stripped",
        "toast.strippedMsg":          "All attachments removed.",
        "toast.importedTitle":        "Build Imported",
        "toast.importedMsg":          "Build successfully imported.",
        "toast.exportedTitle":        "Backup Exported",
        "toast.exportedMsg":          "All builds exported.",
        "toast.exportedCountMsg":     "{n} build(s) saved to file.",
        "toast.noBuildsToExportTitle": "Nothing to Export",
        "toast.noBuildsToExport":     "No saved builds to export.",
        "toast.deletedTitle":         "Build Deleted",
        "toast.invalidCode":          "Invalid share code.",
        "toast.invalidFile":          "Invalid backup file.",
        "toast.connectionError":      "Connection Error",
        "toast.backendDown":          "Could not load weapon list.",
        "toast.ammoLoadFailed":       "Could not load ammo data.",
        "toast.serverUnreachable":    "Could not reach the server.",
        "toast.attachListFailed":     "Could not load attachment list.",
        "toast.attachDataFailed":     "Could not load attachment data.",
        "toast.networkHintDev":       "Is the backend running?",
        "toast.networkHintProd":      "Check your internet connection.",
        "toast.syncNoticeTitle":      "Daily Data Sync",
        "toast.syncNoticeMsg":        "The server is resyncing tarkov.dev data at 4:00 AM UTC+8. The site may be briefly unavailable (~30s).",
        "toast.storageFull":          "Storage Full",
        "toast.storageFullMsg":       "Delete some saved builds to make room.",
        "toast.saveFailed":           "Save Failed",
        "toast.saveFailedMsg":        "Please enter a build name.",
        "toast.codeCopiedMsg":        "Build code copied to clipboard.",
        "toast.copyFailed":           "Copy Failed",
        "toast.clipboardFailed":      "Could not access clipboard.",
        "toast.loadFailed":           "Load Failed",
        "toast.codeCorrupted":        "Build code is corrupted.",
        "toast.unknownWeapon":        "Unknown weapon in build code.",
        "toast.buildLoaded":          "Build Loaded",
        "toast.loadedSuffix":         " loaded.",
        "toast.partialLoad":          "Partial Load",
        "toast.partialLoadMsg":       "{n} attachment(s) could not be found.\nGame data may have been updated.",
        "toast.importFailed":         "Import Failed",
        "toast.invalidBuildCode":     "Invalid or corrupted build code.",
        "toast.backupImportedTitle":  "Backup Imported",
        "toast.backupLoadedMsg":      "{n} build(s) loaded.",
        "toast.backupMergedMsg":      "{n} build(s) imported.",
        "toast.readFileFailed":       "Could not read backup file.",
        "toast.pasteFailed":          "Paste Failed",
        "toast.attachmentConflict":   "Attachment Conflict",
        "toast.mobileWarningTitle":   "Mobile Device Detected",
        "toast.mobileWarningMsg":     "This site is optimised for desktop. For the best experience, enable \"Request Desktop Site\" in your browser or visit on a PC.",
        // Conflict reason prefixes
        "conflict.incompatibleWith":  "Is incompatible with: ",
        "conflict.slot":              "Conflicts with slot: ",
        "conflict.blockedBy":         "Blocked by installed item: ",
        // UI labels
        "ui.cancel":              "Cancel",
        "ui.overwrite":           "Overwrite",
        "ui.confirm":             "Confirm?",
        "ui.load":                "Load",
        "ui.copy":                "Copy",
        "ui.skip":                "Skip",
        "ui.rename":              "Rename",
        "ui.continue":            "Continue",
        "ui.noAmmoFound":         "No ammo found",
        "ui.selectAttFor":        "Select Attachment for ",
        // Weapon class display names
        "class.Assault rifle":    "Assault Rifles",
        "class.Assault carbine":  "Assault Carbines",
        "class.Marksman rifle":   "Marksman Rifles",
        "class.Sniper rifle":     "Sniper Rifles",
        "class.Machinegun":       "Light Machine Guns",
        "class.Machine gun":      "Light Machine Guns",
        "class.Machine Gun":      "Light Machine Guns",
        "class.SMG":              "Submachine Guns",
        "class.Submachine gun":   "Submachine Guns",
        "class.Shotgun":          "Shotguns",
        "class.Handgun":          "Handguns",
        "class.Revolver":         "Revolvers",
        "class.Grenade launcher": "Grenade Launchers",
        "class.Grenade Launcher": "Grenade Launchers",
        "class.Primary":          "Other",
        // Slot names (keys match the display names returned by the tarkov.dev API)
        "slot.Barrel":            "Barrel",
        "slot.Muzzle":            "Muzzle",
        "slot.Stock":             "Stock",
        "slot.Handguard":         "Handguard",
        "slot.Scope":             "Scope",
        "slot.Front Sight":       "Front Sight",
        "slot.Rear Sight":        "Rear Sight",
        "slot.Pistol Grip":       "Pistol Grip",
        "slot.Magazine":          "Magazine",
        "slot.Gas Block":         "Gas Block",
        "slot.Foregrip":          "Foregrip",
        "slot.Ch. Handle":        "Charging Handle",
        "slot.Mount":             "Mount",
        "slot.Tactical":          "Tactical",
        "slot.Bipod":             "Bipod",
        "slot.Receiver":          "Receiver",
        "slot.Ubgl":              "UBGL",
        "slot.Grip":              "Grip",
        "slot.Trigger":           "Trigger",
        "slot.Hammer":            "Hammer",
        "slot.Chamber":           "Chamber",
        "slot.Catch":             "Catch",
    },
    zh: {
        // Header
        "btn.about":            "关于",
        "btn.builds":           "配置",
        "btn.news":             "新闻",
        // News page
        "news.title":           "最新动态",
        "news.loading":         "加载中...",
        "news.loadError":       "无法加载内容，请检查网络连接。",
        "news.postNotFound":    "文章不存在。",
        "news.noPosts":         "暂无文章，敬请期待。",
        "news.backToList":      "返回动态列表",
        "ui.close":             "关闭",
        // Weapon selector toggles
        "btn.primary":          "主武器",
        "btn.pistol":           "手枪",
        "btn.caliber":          "口径",
        "btn.class":            "类型",
        // Left build area buttons
        "btn.back":             "← 返回",
        "btn.reset":            "重置配件",
        "btn.strip":            "清除配件",
        "btn.saveShare":        "保存 / 分享",
        "btn.gunBuilds":        "加载配置",
        // Search placeholders
        "placeholder.gunSearch":  "输入搜索...",
        "placeholder.attSearch":  "输入搜索...",
        // Right panel placeholder
        "placeholder.modding":    "选择配件槽位即可开始改装...",
        "placeholder.rightClick": "右键配件可将其移除",
        "placeholder.longPress":  "长按已安装的配件可将其移除",
        // Mobile tab bar
        "tab.build":               "改装",
        "tab.attachments":         "配件",
        "modal.installAttachment": "安装配件",
        "modal.weight":            "重量",
        "modal.recoil":            "后坐力 %",
        "modal.ergo":              "人机工效",
        "modal.evoErgo":           "Evo人机工效",
        "modal.cancel":            "取消",
        "modal.install":           "安装",
        "modal.remove":            "移除",
        // Stats panel
        "stats.title":              "当前配置",
        "stats.ergo":               "人机工效",
        "stats.verRecoil":          "垂直后坐力",
        "stats.horRecoil":          "水平后坐力",
        "stats.weight":             "重量：",
        "stats.eed":                "Evo人机Delta",
        "stats.eedLabel":           "Evo人机Delta（EED）：",
        "stats.overswing":          "过摆：",
        "stats.armStamina":         "手臂耐力",
        "stats.fullMag":            "装满弹匣",
        "stats.strengthLv":         "力量等级",
        "stats.selectWeapon":       "请选择武器以开始",
        "stats.beta":               "BETA",
        "stats.staminaDisclaimer":  "站立时手臂耐力耗尽所需秒数。\n预计偏差 \u00B10.5s",    
        "stats.eedDesc":            "EED表示当前配置距过摆阈值（EED = 0）的距离，此值越高越好。相同EED的两种配置过摆表现相同；超重会影响开镜速度，但不影响过摆。",
        "stats.overswingDesc":      "表示开镜后准星是否会摆过中心点。当EED为负时发生。预计偏差 \u00B12 EED。",
        "stats.equipErgoLabel":     "装备人机工效修正",
        "stats.equipErgoDisclaimer":"所佩戴装备（头盔、防弹衣、背包、战术背心、面罩、护目镜）的人机工效惩罚总和 - 请根据游戏中的实际装备进行设置。",
        "stats.eedWarnTooltip":     "EED 接近过摆阈值。若您的装备降低了人机工效，此配置可能发生过摆 - 建议设置装备人机工效修正。",
        "stats.yes":                "是",
        "stats.no":                 "否",
        // Attachment tree
        "tree.title":             "配件树",
        // Attachment table column headers
        "th.name":                "名称",
        "th.weight":              "重量 (kg)",
        "th.recoil":              "后坐力",
        "th.ergo":                "人机工效",
        "th.evoErgo":             "Evo人机工效",
        // Build manager modals
        "modal.save":             "保存配置",
        "modal.share":            "分享配置",
        "modal.import":           "导入配置",
        "modal.backup":           "备份",
        "modal.builds":           "已保存配置",
        "modal.saveName":         "配置名称...",
        "modal.saveBtn":          "保存",
        "modal.copyBtn":          "复制配置码",
        "modal.copied":           "已复制！",
        "modal.pasteBtn":         "粘贴",
        "modal.importBtn":        "导入",
        "modal.exportBtn":        "导出备份",
        "modal.importFile":       "从文件导入",
        "modal.dropToImport":     "松开以导入文件",
        "modal.searchBuilds":     "按名称或武器搜索...",
        "modal.searchBuildsGun":  "按配置名称搜索...",
        "modal.noBuilds":         "暂无保存的配置。",
        "modal.noMatch":          "未找到匹配的配置。",
        "modal.saveAndShare":     "保存 & 分享",
        "modal.pasteBuildCode":   "粘贴配置码以导入...",
        "modal.alreadyExists":    " 在此武器中已存在。",
        "modal.overwriteConfirm": "是否覆盖该配置？",
        "modal.importBackup":     "导入备份",
        "modal.importMode":       "导入模式",
        "modal.backupInfo":       "{v} 版本中的 {n} 个配置",
        "modal.mergeBtn":         "合并到现有配置",
        "modal.overwriteAllBtn":  "覆盖全部",
        "modal.versionMismatch":  "\u26A0 版本不匹配",
        "modal.versionMismatchDesc": "此备份由版本 {version} 创建（当前版本：{current}），可能存在兼容问题。",
        "modal.areYouSure":       "确定要继续吗？",
        "modal.nameConflicts":    "名称冲突",
        "modal.conflictsDesc":    "以下配置已存在，请选择处理方式。",
        "modal.conflict":         "个冲突",
        "modal.conflicts":        "个冲突",
        "modal.confirmAll":       "全部确认",
        "modal.newBuildName":     "新配置名称...",
        "modal.nameEmpty":        "名称不能为空。",
        "modal.nameTaken":        "该名称在此武器中已存在。",
        "modal.nameDuplicate":    "此次导入中存在重复名称。",
        // About dialog
        "about.title":            "关于EFTForge",
        "about.reportBug":        "反馈问题",
        "about.disclaimer1":      "游戏内容及素材均为<strong style=\"color:#bbb;\">Battlestate Games</strong>及其授权方的商标和著作权所有。保留所有权利。",
        "about.disclaimer2":      "EFTForge是一款非官方的工具，与Battlestate Games公司无关联，未获其认可，亦不存在任何形式的官方合作关系。",
        "about.dataSource":       "所有游戏内数据来源于",
        "about.copyright":        "\u00A9 2026 Morph1ne. 保留所有权利。",
        // Toast messages
        "toast.savedTitle":           "配置已保存",
        "toast.savedMsg":             "配置已成功保存。",
        "toast.resetTitle":           "配置已重置",
        "toast.resetMsg":             "配置已恢复到出厂状态。",
        "toast.strippedTitle":        "配件已清除",
        "toast.strippedMsg":          "所有附件已移除。",
        "toast.importedTitle":        "配置已导入",
        "toast.importedMsg":          "配置导入成功。",
        "toast.exportedTitle":        "备份已导出",
        "toast.exportedMsg":          "所有配置已导出。",
        "toast.exportedCountMsg":     "已导出 {n} 个配置。",
        "toast.noBuildsToExportTitle": "无法导出",
        "toast.noBuildsToExport":     "暂无可导出的配置。",
        "toast.deletedTitle":         "配置已删除",
        "toast.invalidCode":          "无效的配置码。",
        "toast.invalidFile":          "无效的备份文件。",
        "toast.connectionError":      "连接错误",
        "toast.backendDown":          "无法加载武器列表。",
        "toast.ammoLoadFailed":       "无法加载弹药数据。",
        "toast.serverUnreachable":    "无法连接服务器。",
        "toast.attachListFailed":     "无法加载配件列表。",
        "toast.attachDataFailed":     "无法加载配件数据。",
        "toast.networkHintDev":       "请检查后端是否正在运行。",
        "toast.networkHintProd":      "请检查您的网络连接。",
        "toast.syncNoticeTitle":      "每日数据同步",
        "toast.syncNoticeMsg":        "服务器将于每日 UTC+8 凌晨4:00 同步 tarkov.dev 数据，网站可能短暂无法访问（约30秒）。",
        "toast.storageFull":          "存储空间已满",
        "toast.storageFullMsg":       "请删除部分已保存的配置以腾出空间。",
        "toast.saveFailed":           "保存失败",
        "toast.saveFailedMsg":        "请输入配置名称。",
        "toast.codeCopiedMsg":        "配置码已复制到剪贴板。",
        "toast.copyFailed":           "复制失败",
        "toast.clipboardFailed":      "无法访问剪贴板。",
        "toast.loadFailed":           "加载失败",
        "toast.codeCorrupted":        "配置码已损坏。",
        "toast.unknownWeapon":        "配置码中包含未知武器。",
        "toast.buildLoaded":          "配置已加载",
        "toast.loadedSuffix":         " 已加载。",
        "toast.partialLoad":          "部分加载",
        "toast.partialLoadMsg":       "{n} 个配件无法找到。\n游戏数据可能已更新。",
        "toast.importFailed":         "导入失败",
        "toast.invalidBuildCode":     "无效或已损坏的配置码。",
        "toast.backupImportedTitle":  "备份已导入",
        "toast.backupLoadedMsg":      "已加载 {n} 个配置。",
        "toast.backupMergedMsg":      "已导入 {n} 个配置。",
        "toast.readFileFailed":       "无法读取备份文件。",
        "toast.pasteFailed":          "粘贴失败",
        "toast.attachmentConflict":   "配件冲突",
        "toast.mobileWarningTitle":   "检测到移动设备",
        "toast.mobileWarningMsg":     "本站针对桌面端优化。如需最佳体验，请在浏览器中开启「请求桌面版网站」，或使用电脑访问。",
        // Conflict reason prefixes
        "conflict.incompatibleWith":  "与以下配件冲突：",   
        "conflict.slot":              "配件冲突：",
        "conflict.blockedBy":         "被已安装配件阻止：",
        // UI labels
        "ui.cancel":              "取消",
        "ui.overwrite":           "覆盖",
        "ui.confirm":             "确认？",
        "ui.load":                "加载",
        "ui.copy":                "复制",
        "ui.skip":                "跳过",
        "ui.rename":              "重命名",
        "ui.continue":            "继续",
        "ui.noAmmoFound":         "未找到弹药",
        "ui.selectAttFor":        "选择配件：",
        // Weapon class display names
        "class.Assault rifle":    "突击步枪",
        "class.Assault carbine":  "突击卡宾枪",
        "class.Marksman rifle":   "精确射手步枪",
        "class.Sniper rifle":     "狙击步枪",
        "class.Machinegun":       "轻机枪",
        "class.Machine gun":      "轻机枪",
        "class.Machine Gun":      "轻机枪",
        "class.SMG":              "冲锋枪",
        "class.Submachine gun":   "冲锋枪",
        "class.Shotgun":          "霰弹枪",
        "class.Handgun":          "手枪",
        "class.Revolver":         "左轮手枪",
        "class.Grenade launcher": "榴弹发射器",
        "class.Grenade Launcher": "榴弹发射器",
        "class.Primary":          "其他",
        // Slot names (keys match the display names returned by the tarkov.dev API)
        "slot.Barrel":            "枪管",
        "slot.Muzzle":            "枪口",
        "slot.Stock":             "枪托",
        "slot.Handguard":         "护木",
        "slot.Scope":             "瞄具",
        "slot.Front Sight":       "准星",
        "slot.Rear Sight":        "照门",
        "slot.Pistol Grip":       "手枪握把",
        "slot.Magazine":          "弹匣",
        "slot.Gas Block":         "导气管",
        "slot.Foregrip":          "前握把",
        "slot.Ch. Handle":        "拉机柄",
        "slot.Mount":             "导轨",
        "slot.Tactical":          "战术配件",
        "slot.Bipod":             "脚架",
        "slot.Receiver":          "上机匣",
        "slot.Ubgl":              "下挂榴弹发射器",
        "slot.Grip":              "握把",
        "slot.Trigger":           "扳机",
        "slot.Hammer":            "击锤",
        "slot.Chamber":           "弹膛",
        "slot.Catch":             "空仓挂机柄",
    },
};

function t(key) {
    const lang = (window.EFTForge.state && window.EFTForge.state.lang) || "en";
    const table = _TRANSLATIONS[lang] || _TRANSLATIONS["en"];
    return (table[key] !== undefined) ? table[key] : ((_TRANSLATIONS["en"][key] !== undefined) ? _TRANSLATIONS["en"][key] : key);
}

function tFmt(key, vars) {
    let str = t(key);
    for (const [k, v] of Object.entries(vars)) {
        str = str.replaceAll(`{${k}}`, String(v));
    }
    return str;
}

function tSlot(rawSlotName) {
    const translated = t(`slot.${rawSlotName}`);
    if (translated === `slot.${rawSlotName}`) return rawSlotName;
    return translated;
}

function tClass(rawClassName) {
    const translated = t(`class.${rawClassName}`);
    if (translated === `class.${rawClassName}`) return rawClassName;
    return translated;
}

window.EFTForge.lang = { t, tFmt, tSlot, tClass };

// Expose as globals so template literals in rendering modules can call them directly
window.t      = t;
window.tFmt   = tFmt;
window.tSlot  = tSlot;
window.tClass = tClass;
