window.EFTForge = window.EFTForge || {};

const _TRANSLATIONS = {
    en: {
        // Header
        "btn.about":            "About",
        "btn.builds":           "Builds",
        "btn.news":             "News",
        // News page
        "news.title":           "NEWS",
        "news.loading":         "Loading...",
        "news.loadError":       "Could not load content. Please check your connection.",
        "news.postNotFound":    "Post not found.",
        "news.noPosts":         "No posts yet. Check back soon.",
        "news.backToList":      "Back to News",
        "ui.close":             "Close",
        // Weapon selector toggles
        "btn.primary":          "Primary",
        "btn.pistol":           "Pistol",
        "btn.caliber":          "Caliber",
        "btn.class":            "Class",
        // Left build area buttons
        "btn.back":             "\u2190 Back",
        "btn.reset":            "Reset Build",
        "btn.strip":            "Strip Build",
        "btn.saveShare":        "Save / Share",
        "btn.gunBuilds":        "Explore Builds",
        // Search placeholders
        "placeholder.gunSearch":  "Start typing to search...",
        "placeholder.attSearch":  "Start typing to search...",
        // Right panel placeholder
        "placeholder.modding":    "Select an attachment slot to begin modding...",
        "placeholder.rightClick": "Right click an attachment to remove it",
        "placeholder.longPress":  "Swipe left on an installed attachment to remove it",
        // Mobile tab bar
        "tab.build":               "Build",
        "tab.attachments":         "Attachments",
        "modal.installAttachment": "Install Attachment",
        "modal.weight":            "WEIGHT",
        "modal.recoil":            "RECOIL %",
        "modal.ergo":              "ERGONOMICS",
        "modal.evoErgo":           "EVO ERGO",
        "modal.cancel":            "Cancel",
        "modal.install":           "Install",
        "modal.remove":            "Remove",
        // Stats panel
        "stats.title":              "CURRENT BUILD",
        "stats.compareMode":        "COMPARE MODE",
        "stats.ergo":               "Ergonomics",
        "stats.verRecoil":          "Ver. Recoil",
        "stats.horRecoil":          "Hor. Recoil",
        "stats.weight":             "Weight:",
        "stats.eed":                "EvoErgoDelta",
        "stats.eedLabel":           "EED:",
        "stats.overswing":          "OverSwing:",
        "stats.armStamina":         "Arm Stamina",
        "stats.fullMag":            "Assume Full Magazine",
        "stats.ammoDisabledTitle":  "Selection Disabled",
        "stats.ammoDisabledTip":    "Assume Full Magazine is off",
        "stats.strengthLv":         "Strength Level",
        "stats.selectWeapon":       "Select a weapon to begin",
        "stats.beta":               "BETA",
        "stats.staminaDisclaimer":  "Seconds until arm stamina depletes while standing.\nExpected deviation \u00B10.5s",
        "stats.eedDesc":            "How far your build is from the overswing threshold at EED = 0, higher is better. Two builds with the same EED behave identically for overswing; being overweight affects ADS speed but not overswing.",
        "stats.overswingDesc":      "Whether the gun will swing over the center point of aiming after ADS. Occurs when EED is negative. Estimated inaccuracy of \u00B12 EED.",
        "stats.equipErgoLabel":     "Equipment Ergonomics Modifier",
        "stats.equipErgoDisclaimer":"The total Ergonomics penalty from worn equipment (headgear, armor, backpack, rig, facecover, eyewear) - set this to match your in-game gear.",
        "stats.eedWarnTooltip":         "EED is close to the overswing threshold. If your equipment reduces ergonomics, this build may overswing - consider setting your Equipment Ergonomics Modifier.",
        "stats.configEquipErgoTooltip": "Configure equipment ergonomics modifier",
        "stats.configStrengthTooltip":  "Configure strength level",
        "stats.yes":                "YES",
        "stats.no":                 "NO",
        "stats.overswingDeprecated": "As of patch 1.0.4.0.44026, the overswing mechanic has been deprecated.",
        // Hidden stats
        "hidden.showBtn":           "Show hidden stats",
        "hidden.hideBtn":           "Hide hidden stats",
        "hidden.title":             "HIDDEN STATS",
        "hidden.aimPlane":          "Aim Deviation",
        "hidden.aimSens":           "Aim Sensitivity",
        "hidden.camAngleStep":      "Camera Angle Step",
        "hidden.camSnap":           "Camera Snap",
        "hidden.mountCamSnap":      "Mount Camera Snap",
        "hidden.mountHRec":         "Mount Horizontal Recoil",
        "hidden.mountVRec":         "Mount Vertical Recoil",
        "hidden.mountBreath":       "Mount Breath Sway",
        "hidden.devCurve":          "Deviation Curve",
        "hidden.devMax":            "Max Deviation",
        "hidden.recAngle":          "Recoil Angle",
        "hidden.recHandRot":        "Hand Rotation",
        "hidden.recDispersion":     "Recoil Dispersion",
        "hidden.recForceBack":      "Recoil Backwards Force",
        "hidden.recForceUp":        "Recoil Upwards Force",
        "hidden.recReturnSpeed":    "Recoil Return Speed",
        "hidden.tip.aimPlane":      "Base spread of the weapon when aiming down sights",
        "hidden.tip.aimSens":       "How sharply the camera responds to mouse input while aiming",
        "hidden.tip.camAngleStep":  "Increment at which the camera angle snaps per step",
        "hidden.tip.camSnap":       "How quickly the camera returns to center after recoil",
        "hidden.tip.devCurve":      "The curve function applied to shot deviation over time",
        "hidden.tip.devMax":        "Maximum possible deviation from point of aim",
        "hidden.tip.mountCamSnap":  "Multiplier for how aggressively the camera re-centers while mounted",
        "hidden.tip.mountHRec":     "Recoil multiplier applied when firing from a mount, horizontal axis",
        "hidden.tip.mountVRec":     "Recoil multiplier applied when firing from a mount, vertical axis",
        "hidden.tip.mountBreath":   "Sway multiplier for out-of-breath penalty while mounted",
        "hidden.tip.recAngle":      "Angle offset direction of the recoil pattern",
        "hidden.tip.recHandRot":    "Recoil hand rotation multiplier category",
        "hidden.tip.recDispersion": "Spread applied to successive shots in the recoil pattern",
        "hidden.tip.recForceBack":  "Physical force pushing the weapon back into the shooter on fire",
        "hidden.tip.recForceUp":    "Physical force pushing the weapon upward on fire",
        "hidden.tip.recReturnSpeed":"How quickly the weapon returns to its base position between shots",
        "hidden.tooltip":           "Stats marked ? are unavailable for weapons not yet in the game data source",
        // Price view
        "stats.buildCost":          "BUILD COST",
        "stats.pveModeLabel":       "PVE",
        "stats.totalCost":          "Total",
        "stats.ammoRow":            "Ammo",
        "stats.ubglAmmoRow":        "UBGL Ammo",
        "stats.buildView":          "Build",
        "stats.factoryIncluded":    "Factory",
        "stats.priceView":          "Price",
        "stats.fleaMarket":         "Fetching Flea Market Info",
        "stats.fleaLabel":          "Flea",
        "stats.fleaTs":             "Last Flea Fetch:",
        "stats.refetchFlea":        "Refetch Flea",
        "stats.refetchingFlea":     "Refetching",
        "stats.fetchingFleaPrices": "Fetching Flea Prices",
        "stats.fleaFetching":       "Fetching prices for",
        "stats.fleaFetchingItems":  "items...",
        "stats.fleaCached":         "All prices cached.",
        "stats.fleaUpdated":        "Prices updated.",
        "stats.traderLevels":       "Set Trader Levels",
        "stats.traderLevelsAll":    "All",
        // Attachment tree
        "tree.title":             "WORKBENCH",
        "tree.swipeHint":         "Swipe left to remove attachment",
        // Attachment table column headers
        "th.name":                "Name",
        "th.weight":              "Weight (kg)",
        "th.recoil":              "Recoil",
        "th.ergo":                "Ergonomics",
        "th.evoErgo":             "EvoErgo",
        // Build manager modals
        "modal.save":             "SAVE BUILD",
        "modal.share":            "SHARE BUILD",
        "modal.import":           "IMPORT BUILD",
        "modal.backup":           "BACKUP",
        "modal.builds":           "SAVED BUILDS",
        "modal.exploreBuilds":    "EXPLORE BUILDS",
        "modal.myBuilds":         "MY BUILDS",
        "modal.communityBuilds":  "COMMUNITY BUILDS",
        "modal.publishBtn":       "Publish",
        "modal.publishedBtn":     "Published",
        "modal.unlistBtn":        "Unlist",
        "modal.noPublicBuilds":   "No community builds yet. Be the first!",
        "modal.publicBuildsError": "Could not load community builds.",
        "modal.communityBuildsUnavailable": "Community builds are currently unavailable. Please try again later.",
        "modal.publishLoading":   "Loading community builds...",
        "modal.anonymousAuthor":  "Tarkov Citizen",
        "cb.featured":            "Featured",
        "cb.statWeight":          "Weight",
        "cb.statOverswing":       "Overswing",
        "cb.statCost":            "Cost",
        "cb.loads":               "loads",
        "cb.infoTooltip":         "Community builds are loadouts shared by players for this specific weapon.\n\nSave a build under Save / Share and hit Publish to share yours with the community.\n\nOutstanding builds can be featured by the admin, so make it count!\n\nCheck the Leaderboard to see the top trending and all-time builds. Give your favorites a like so they make the cut!",
        "cb.limitReachedTitle":   "Build Limit Reached",
        "cb.limitReachedMsg":     "This gun has reached the community builds limit. Please contact the website owner to resolve this.",
        "cb.searchPlaceholder":   "Search builds...",
        "cb.noMatch":             "No community builds match your search.",
        "cb.sort.default":        "Featured",
        "cb.sort.newest":         "Newest",
        "cb.sort.loads":          "Most Loaded",
        "cb.sort.rating":         "Highest Rated",
        "cb.sort.eed":            "Highest EED",
        "cb.sort.recoil":         "Best V.Recoil",
        "cb.sort.price":          "Cheapest",
        "modal.saveName":         "Build name...",
        "modal.saveBtn":          "Save",
        "modal.copyBtn":          "Copy Share Code",
        "modal.copied":           "Copied!",
        "modal.pasteBtn":         "Paste",
        "modal.importBtn":        "Import",
        "modal.exportBtn":        "Export Backup",
        "modal.importFile":       "Import from File",
        "modal.dropToImport":     "Drop file to import",
        "modal.searchBuilds":     "Search by build name or weapon...",
        "modal.searchBuildsGun":  "Search by build name...",
        "modal.noBuilds":         "No saved builds yet.",
        "modal.publishHint":      "To publish a build, save it first, then use the Publish button below.",
        "modal.noMatch":          "No builds match your search.",
        "modal.saveAndShare":     "SAVE & SHARE",
        "modal.pasteBuildCode":   "Paste build code to import...",
        "modal.alreadyExists":    " already exists for this weapon.",
        "modal.overwriteConfirm": "Do you want to overwrite it?",
        "modal.restoreTitle":     "Unfinished Build",
        "modal.restoreSubtitle":  "You were mid-build on this weapon. Continue where you left off?",
        "modal.restoreContinue":  "Continue",
        "modal.restoreAbandon":   "Abandon",
        "modal.discardTitle":     "UNSAVED CHANGES",
        "modal.discardSubtitle":  "You have unsaved changes. Are you sure you want to discard them?",
        "modal.discardConfirm":   "Yes",
        "modal.discardCancel":    "No",
        "modal.importBackup":     "IMPORT BACKUP",
        "modal.importMode":       "IMPORT MODE",
        "modal.backupInfo":       "{n} build(s) from version {v}",
        "modal.mergeBtn":         "Merge into Existing",
        "modal.overwriteAllBtn":  "Overwrite All",
        "modal.versionMismatch":  "\u26A0 Version Mismatch",
        "modal.versionMismatchDesc": "This backup was created with {version} (current: {current}). It may cause issues.",
        "modal.areYouSure":       "ARE YOU SURE?",
        "modal.nameConflicts":    "NAME CONFLICTS",
        "modal.conflictsDesc":    "These builds already exist. Choose how to handle each one.",
        "modal.conflict":         "conflict",
        "modal.conflicts":        "conflicts",
        "modal.confirmAll":       "Confirm All",
        "modal.newBuildName":     "New build name...",
        "modal.nameEmpty":        "Name cannot be empty.",
        "modal.nameTaken":        "That name already exists for this weapon.",
        "modal.nameDuplicate":    "Duplicate rename within this import.",
        // About dialog
        "about.title":            "ABOUT EFTForge",
        "about.reportBug":        "Report Bug",
        "about.disclaimer1":      "Game content and materials are trademarks and copyrights of <strong style=\"color:#bbb;\">Battlestate Games</strong> and its licensors. All rights reserved.",
        "about.disclaimer2":      "EFTForge is an unofficial fan-made tool and is not affiliated with, endorsed by, or in any way officially connected with Battlestate Games.",
        "about.dataSource":       "All in-game data is sourced from the",
        "about.copyright":        "\u00A9 2026 Morph1ne. All Rights Reserved.",
        // Toast messages
        "toast.savedTitle":           "Build Saved",
        "toast.savedMsg":             "Your build has been saved.",
        "toast.resetTitle":           "Build Reset",
        "toast.resetMsg":             "Build has been reset to factory.",
        "toast.strippedTitle":        "Build Stripped",
        "toast.strippedMsg":          "All attachments removed.",
        "toast.importedTitle":        "Build Imported",
        "toast.importedMsg":          "Build successfully imported.",
        "toast.exportedTitle":        "Backup Exported",
        "toast.exportedMsg":          "All builds exported.",
        "toast.exportedCountMsg":     "{n} build(s) saved to file.",
        "toast.noBuildsToExportTitle": "Nothing to Export",
        "toast.noBuildsToExport":     "No saved builds to export.",
        "modal.deletePublishedTitle": "DELETE PUBLISHED BUILD",
        "modal.deletePublishedBody":  "This build is published to the community. Deleting it will also remove it from the community builds list.",
        "modal.deleteAndUnlist":      "Delete & Unlist",
        "toast.deletedTitle":         "Build Deleted",
        "toast.invalidCode":          "Invalid share code.",
        "toast.invalidFile":          "Invalid backup file.",
        "toast.connectionError":      "Connection Error",
        "toast.backendDown":          "Could not load weapon list.",
        "toast.ammoLoadFailed":       "Could not load ammo data.",
        "toast.serverUnreachable":    "Could not reach the server.",
        "toast.attachListFailed":     "Could not load attachment list.",
        "toast.attachDataFailed":     "Could not load attachment data.",
        "toast.networkHintDev":       "Is the backend running?",
        "toast.networkHintProd":      "Check your internet connection.",
        "toast.syncNoticeTitle":      "Daily Data Sync",
        "toast.syncNoticeMsg":        "The server is resyncing tarkov.dev data at 4:00 AM UTC+8. The site may be briefly unavailable (~1 minute).",
        "toast.storageFull":          "Storage Full",
        "toast.storageFullMsg":       "Delete some saved builds to make room.",
        "toast.saveFailed":           "Save Failed",
        "toast.saveFailedMsg":        "Please enter a build name.",
        "toast.codeCopiedMsg":        "Build code copied to clipboard.",
        "toast.copyFailed":           "Copy Failed",
        "toast.clipboardFailed":      "Could not access clipboard.",
        "toast.loadFailed":           "Load Failed",
        "toast.codeCorrupted":        "Build code is corrupted.",
        // Publish / unlist toasts
        "toast.publishSuccess":       "Build Published",
        "toast.publishSuccessMsg":    "Your build is now live for the community!",
        "toast.publishFailed":        "Publish Failed",
        "toast.publishRateLimit":     "Please wait before publishing again. (1 minute)",
        "toast.publishLimitReached":  "This gun has reached the community builds limit (500). Please contact the website owner to resolve this.",
        "toast.publishBanned":        "You are banned from publishing builds.",
        "toast.unlistSuccess":        "Build Unlisted",
        "toast.unlistSuccessMsg":     "Your build has been removed from the community.",
        "toast.unlistFailed":         "Unlist Failed",
        // Publish confirm panel
        "publish.confirm":            "You are about to publish this build for all players.",
        "publish.confirmSub":         "Once published, it cannot be edited.",
        "publish.nameWarning":        "WARNING! Your custom build name will be public and linked to your identity. Offensive, illegal, or abusive names will be traced back to you by the admin and there will be consequences.",
        "publish.btnCancel":          "Cancel",
        "publish.btnModify":          "Modify",
        "publish.btnConfirm":         "Confirm Publish",
        "publish.publishing":         "Publishing...",
        "publish.mobileTray":         "Review & Publish",
        "publish.slotLockedTitle":    "Reviewing Build",
        "publish.slotLockedMsg":      "You are in publish confirmation. Click Modify to change attachments.",
        // Admin push notifications
        "notify.bannedTitle":         "Publishing Restricted",
        "notify.banned":              "You have been temporarily banned from publishing builds. Duration: {duration}. You will be unbanned on {date}.",
        "notify.bannedPermanent":     "You have been permanently banned from publishing builds.",
        "notify.banReason":           "Reason: {reason}",
        "notify.unbannedTitle":       "Publishing Restored",
        "notify.unbanned":            "Your publishing restriction has been lifted. You can now publish builds again.",
        "notify.unlistedTitle":       "Build Removed",
        "notify.buildUnlisted":       "Your build \"{name}\" was removed by an admin.",
        "notify.announcementTitle":   "Server Announcement",
        "toast.unknownWeapon":        "Unknown weapon in build code.",
        "toast.buildLoaded":          "Build Loaded",
        "toast.loadedSuffix":         " loaded.",
        "toast.stateRestored":        "State Restored",
        "toast.stateRestoredMsg":     "Your last build snapshot has been restored.",
        "toast.partialLoad":          "Partial Load",
        "toast.partialLoadMsg":       "{n} attachment(s) could not be found.\nGame data may have been updated.",
        "toast.importFailed":         "Import Failed",
        "toast.invalidBuildCode":     "Invalid or corrupted build code.",
        "toast.backupImportedTitle":  "Backup Imported",
        "toast.backupLoadedMsg":      "{n} build(s) loaded.",
        "toast.backupMergedMsg":      "{n} build(s) imported.",
        "toast.readFileFailed":       "Could not read backup file.",
        "toast.pasteFailed":          "Paste Failed",
        "toast.attachmentConflict":   "Attachment Conflict",
        "toast.mobileWarningTitle":   "Mobile Device Detected",
        "toast.mobileWarningMsg":     "This site is optimised for desktop. For the best experience, enable \"Request Desktop Site\" in your browser or visit on a PC.",
        // Conflict reason prefixes
        "conflict.incompatibleWith":  "Is incompatible with: ",
        "conflict.slot":              "Conflicts with slot: ",
        "conflict.blockedBy":         "Blocked by installed item: ",
        // UI labels
        "ui.cancel":              "Cancel",
        "ui.overwrite":           "Overwrite",
        "ui.confirm":             "Confirm?",
        "ui.load":                "Load",
        "ui.copy":                "Copy",
        "ui.skip":                "Skip",
        "ui.rename":              "Rename",
        "ui.continue":            "Continue",
        "ui.noAmmoFound":         "No ammo found",
        "ui.noGrenade":           "- No grenade -",
        "ui.selectAttFor":        "Select Attachment for ",
        "ui.compare":             "Compare",
        "ui.purchasableOnly":     "Buyable",
        "ui.purchasableOnlyTip":  "Hides attachments not sold by traders at the currently set loyalty levels. Set levels in the Price tab under Set Trader Levels.",
        "ui.taskUnlock":          "Quest: ",
        "ui.compareBaseline":     "BASELINE",
        "ui.compareHintSelect":   "Click any attachment to set it as the comparison baseline",
        "ui.compareHintBaseline": "Baseline set - hover to compare, click to change baseline",
        // Weapon class display names
        "class.Assault rifle":    "Assault Rifles",
        "class.Assault carbine":  "Assault Carbines",
        "class.Marksman rifle":   "Marksman Rifles",
        "class.Sniper rifle":     "Sniper Rifles",
        "class.Machinegun":       "Light Machine Guns",
        "class.Machine gun":      "Light Machine Guns",
        "class.Machine Gun":      "Light Machine Guns",
        "class.SMG":              "Submachine Guns",
        "class.Submachine gun":   "Submachine Guns",
        "class.Shotgun":          "Shotguns",
        "class.Handgun":          "Handguns",
        "class.Revolver":         "Revolvers",
        "class.Grenade launcher": "Grenade Launchers",
        "class.Grenade Launcher": "Grenade Launchers",
        "class.Primary":          "Other",
        // Slot names (keys match the display names returned by the tarkov.dev API)
        "slot.Barrel":            "Barrel",
        "slot.Muzzle":            "Muzzle",
        "slot.Stock":             "Stock",
        "slot.Handguard":         "Handguard",
        "slot.Scope":             "Scope",
        // Attachment ratings
        "rating.like":            "Give the attachment a like!",
        "rating.dislike":         "This attachment is trash, yo",
        // Build ratings
        "cb.rating.like":         "Give this build a like!",
        // Leaderboard
        "btn.leaderboard":              "Leaderboards",
        "lb.title":                     "LEADERBOARDS",
        "lb.builds":                    "Community Builds",
        "lb.attachments":               "Attachments",
        "lb.period2w":                  "Last 2 Weeks",
        "lb.periodAll":                 "All Time",
        "lb.sortLikes":                 "Most Liked",
        "lb.sortDislikes":              "Most Disliked",
        "lb.categoryAll":               "All Slots",
        "lb.buildsInfo":                "Top 10 builds from the last 2 weeks will be nominated as Featured Builds, with a fully modded preview image set up and linked directly to the build!",
        "lb.empty":                     "No entries yet.",
        "lb.loadError":                 "Could not load leaderboard.",
        "lb.top10":                     "Top 10",
        "lb.top20":                     "Top 20",
        "lb.top50":                     "Top 50",
        "lb.top100":                    "Top 100",
        "lb.likes":                     "likes",
        "lb.dislikes":                  "dislikes",
        "lb.buildLoaded":               "Build Loaded from Leaderboard",
        "lb.gunFilterAll":              "All Guns",
        // Slot names
        "slot.Front Sight":       "Front Sight",
        "slot.Rear Sight":        "Rear Sight",
        "slot.Pistol Grip":       "Pistol Grip",
        "slot.Magazine":          "Magazine",
        "slot.Gas Block":         "Gas Block",
        "slot.Foregrip":          "Foregrip",
        "slot.Ch. Handle":        "Charging Handle",
        "slot.Mount":             "Mount",
        "slot.Tactical":          "Tactical",
        "slot.Bipod":             "Bipod",
        "slot.Receiver":          "Receiver",
        "slot.Ubgl":              "UBGL",
        "slot.Grip":              "Grip",
        "slot.Trigger":           "Trigger",
        "slot.Hammer":            "Hammer",
        "slot.Chamber":           "Chamber",
        "slot.Catch":             "Catch",
    },
    zh: {
        // Header
        "btn.about":            "关于",
        "btn.builds":           "配置",
        "btn.news":             "新闻",
        // News page
        "news.title":           "最新动态",
        "news.loading":         "加载中...",
        "news.loadError":       "无法加载内容，请检查网络连接。",
        "news.postNotFound":    "文章不存在。",
        "news.noPosts":         "暂无文章，敬请期待。",
        "news.backToList":      "返回动态列表",
        "ui.close":             "关闭",
        // Weapon selector toggles
        "btn.primary":          "主武器",
        "btn.pistol":           "手枪",
        "btn.caliber":          "口径",
        "btn.class":            "类型",
        // Left build area buttons
        "btn.back":             "← 返回",
        "btn.reset":            "重置配件",
        "btn.strip":            "清除配件",
        "btn.saveShare":        "保存 / 分享",
        "btn.gunBuilds":        "探索配置",
        // Search placeholders
        "placeholder.gunSearch":  "输入搜索...",
        "placeholder.attSearch":  "输入搜索...",
        // Right panel placeholder
        "placeholder.modding":    "选择配件槽位即可开始改装...",
        "placeholder.rightClick": "右键配件可将其移除",
        "placeholder.longPress":  "向左滑动已安装的配件可将其移除",
        // Mobile tab bar
        "tab.build":               "改装",
        "tab.attachments":         "配件",
        "modal.installAttachment": "安装配件",
        "modal.weight":            "重量",
        "modal.recoil":            "后坐力 %",
        "modal.ergo":              "人机工效",
        "modal.evoErgo":           "Evo人机工效",
        "modal.cancel":            "取消",
        "modal.install":           "安装",
        "modal.remove":            "移除",
        // Stats panel
        "stats.title":              "当前配置",
        "stats.compareMode":        "对比模式",
        "stats.ergo":               "人机工效",
        "stats.verRecoil":          "垂直后坐力",
        "stats.horRecoil":          "水平后坐力",
        "stats.weight":             "重量：",
        "stats.eed":                "Evo人机Delta",
        "stats.eedLabel":           "Evo人机Delta（EED）：",
        "stats.overswing":          "过摆：",
        "stats.armStamina":         "手臂耐力",
        "stats.fullMag":            "装满弹匣",
        "stats.ammoDisabledTitle":  "选择已禁用",
        "stats.ammoDisabledTip":    "装满弹匣已关闭",
        "stats.strengthLv":         "力量等级",
        "stats.selectWeapon":       "请选择武器以开始",
        "stats.beta":               "BETA",
        "stats.staminaDisclaimer":  "站立时手臂耐力耗尽所需秒数。\n预计偏差 \u00B10.5s",    
        "stats.eedDesc":            "EED表示当前配置距过摆阈值（EED = 0）的距离，此值越高越好。相同EED的两种配置过摆表现相同；超重会影响开镜速度，但不影响过摆。",
        "stats.overswingDesc":      "表示开镜后准星是否会摆过中心点。当EED为负时发生。预计偏差 \u00B12 EED。",
        "stats.equipErgoLabel":     "装备人机工效修正",
        "stats.equipErgoDisclaimer":"所佩戴装备（头盔、防弹衣、背包、战术背心、面罩、护目镜）的人机工效惩罚总和 - 请根据游戏中的实际装备进行设置。",
        "stats.eedWarnTooltip":         "EED 接近过摆阈值。若您的装备降低了人机工效，此配置可能发生过摆 - 建议设置装备人机工效修正。",
        "stats.configEquipErgoTooltip": "设置装备人机工效修正",
        "stats.configStrengthTooltip":  "设置力量等级",
        "stats.yes":                "是",
        "stats.no":                 "否",
        "stats.overswingDeprecated": "截至补丁 1.0.4.0.44026，过摆机制已被移除。",
        // Hidden stats
        "hidden.showBtn":           "显示隐藏属性",
        "hidden.hideBtn":           "隐藏隐藏属性",
        "hidden.title":             "隐藏属性",
        "hidden.aimPlane":          "瞄准偏差",
        "hidden.aimSens":           "瞄准灵敏度",
        "hidden.camAngleStep":      "相机角度步长",
        "hidden.camSnap":           "相机回中",
        "hidden.mountCamSnap":      "架枪相机回中",
        "hidden.mountHRec":         "架枪水平后坐力",
        "hidden.mountVRec":         "架枪垂直后坐力",
        "hidden.mountBreath":       "架枪呼吸晃动",
        "hidden.devCurve":          "偏差曲线",
        "hidden.devMax":            "最大偏差",
        "hidden.recAngle":          "后坐力角度",
        "hidden.recHandRot":        "后坐手部旋转",
        "hidden.recDispersion":     "后坐力散布",
        "hidden.recForceBack":      "后坐向后作用力",
        "hidden.recForceUp":        "后坐向上作用力",
        "hidden.recReturnSpeed":    "后坐回中速度",
        "hidden.tip.aimPlane":      "开镜状态下武器的基础弹道散布",
        "hidden.tip.aimSens":       "开镜时相机对鼠标输入的响应幅度",
        "hidden.tip.camAngleStep":  "每次步进时摄像机视角的偏移量",
        "hidden.tip.camSnap":       "后坐力结束后相机回正到基准位置的速度",
        "hidden.tip.devCurve":      "随时间变化的弹道偏差曲线函数",
        "hidden.tip.devMax":        "与瞄准点的最大可能偏差",
        "hidden.tip.mountCamSnap":  "架枪状态下相机回正力度倍数",
        "hidden.tip.mountHRec":     "架枪射击时水平后坐力倍数",
        "hidden.tip.mountVRec":     "架枪射击时垂直后坐力倍数",
        "hidden.tip.mountBreath":   "架枪状态下体力耗尽时晃动幅度倍数",
        "hidden.tip.recAngle":      "后坐力模板的偏移方向角度",
        "hidden.tip.recHandRot":    "后坐力手部旋转分类倍数",
        "hidden.tip.recDispersion": "连发射击时后坐力模板的散布范围",
        "hidden.tip.recForceBack":  "射击时将武器向后推动的物理力",
        "hidden.tip.recForceUp":    "射击时将武器向上推动的物理力",
        "hidden.tip.recReturnSpeed":"后坐力结束后武器回正到基准位置的速度",
        "hidden.tooltip":           "标有 ? 的属性目前暂无数据（数据源尚未收录该武器）",
        // Price view
        "stats.buildCost":          "配置价格",
        "stats.pveModeLabel":       "PVE",
        "stats.totalCost":          "合计",
        "stats.ammoRow":            "弹药",
        "stats.ubglAmmoRow":        "下挂榴弹发射器弹药",
        "stats.buildView":          "配件",
        "stats.factoryIncluded":    "原厂",
        "stats.priceView":          "价格",
        "stats.fleaMarket":         "获取跳蚤市场信息",
        "stats.fleaLabel":          "跳蚤",
        "stats.fleaTs":             "上一次跳蚤获取:",
        "stats.refetchFlea":        "刷新价格",
        "stats.refetchingFlea":     "正在获取",
        "stats.fetchingFleaPrices": "正在获取跳蚤价格",
        "stats.fleaFetching":       "正在获取",
        "stats.fleaFetchingItems":  "个物品的价格...",
        "stats.fleaCached":         "价格已缓存。",
        "stats.fleaUpdated":        "价格已更新。",
        "stats.traderLevels":       "设置商人等级",
        "stats.traderLevelsAll":    "全部",
        // Attachment tree
        "tree.title":             "工作台",
        "tree.swipeHint":         "左滑以移除配件",
        // Attachment table column headers
        "th.name":                "名称",
        "th.weight":              "重量 (kg)",
        "th.recoil":              "后坐力",
        "th.ergo":                "人机工效",
        "th.evoErgo":             "Evo人机工效",
        // Build manager modals
        "modal.save":             "保存配置",
        "modal.share":            "分享配置",
        "modal.import":           "导入配置",
        "modal.backup":           "备份",
        "modal.builds":           "已保存配置",
        "modal.exploreBuilds":    "探索配置",
        "modal.myBuilds":         "我的方案",
        "modal.communityBuilds":  "社区方案",
        "modal.publishBtn":       "发布",
        "modal.publishedBtn":     "已发布",
        "modal.unlistBtn":        "下架",
        "modal.noPublicBuilds":   "暂无社区方案，成为第一个发布的人！",
        "modal.publicBuildsError": "无法加载社区方案。",
        "modal.communityBuildsUnavailable": "社区方案功能暂时不可用，请稍后再试。",
        "modal.publishLoading":   "正在加载社区方案...",
        "modal.anonymousAuthor":  "塔科夫市民",
        "cb.featured":            "推荐",
        "cb.statWeight":          "重量",
        "cb.statOverswing":       "过摆",
        "cb.statCost":            "费用",
        "cb.loads":               "次加载",
        "cb.infoTooltip":         "社区方案是玩家们为这把武器分享的配装。\n\n在「保存 / 分享」中保存配装后，点击「发布」即可分享给社区。\n\n优秀的配装有机会被设为推荐方案，用心搭配，让别人看到你的杰作！\n\n查看排行榜，发现最热门及史上最高赞配装。给喜欢的配装点赞，助它登顶！",
        "cb.limitReachedTitle":   "方案数量已达上限",
        "cb.limitReachedMsg":     "该武器的社区方案数量已达到上限，请联系网站管理员处理。",
        "cb.searchPlaceholder":   "搜索方案...",
        "cb.noMatch":             "没有匹配的社区方案。",
        "cb.sort.default":        "推荐优先",
        "cb.sort.newest":         "最新",
        "cb.sort.loads":          "最多加载",
        "cb.sort.rating":         "最高评分",
        "cb.sort.eed":            "最高Evo人机",
        "cb.sort.recoil":         "最低垂直后坐",
        "cb.sort.price":          "最低费用",
        "modal.saveName":         "配置名称...",
        "modal.saveBtn":          "保存",
        "modal.copyBtn":          "复制配置码",
        "modal.copied":           "已复制！",
        "modal.pasteBtn":         "粘贴",
        "modal.importBtn":        "导入",
        "modal.exportBtn":        "导出备份",
        "modal.importFile":       "从文件导入",
        "modal.dropToImport":     "松开以导入文件",
        "modal.searchBuilds":     "按名称或武器搜索...",
        "modal.searchBuildsGun":  "按配置名称搜索...",
        "modal.noBuilds":         "暂无保存的配置。",
        "modal.publishHint":      "如需发布方案，请先保存，再点击下方的发布按钮。",
        "modal.noMatch":          "未找到匹配的配置。",
        "modal.saveAndShare":     "保存 & 分享",
        "modal.pasteBuildCode":   "粘贴配置码以导入...",
        "modal.alreadyExists":    " 在此武器中已存在。",
        "modal.overwriteConfirm": "是否覆盖该配置？",
        "modal.restoreTitle":     "未完成的配置",
        "modal.restoreSubtitle":  "检测到未保存的武器配置，是否继续？",
        "modal.restoreContinue":  "继续",
        "modal.restoreAbandon":   "放弃",
        "modal.discardTitle":     "未保存的更改",
        "modal.discardSubtitle":  "您有未保存的更改。您确定要放弃更改？",
        "modal.discardConfirm":   "是",
        "modal.discardCancel":    "否",
        "modal.importBackup":     "导入备份",
        "modal.importMode":       "导入模式",
        "modal.backupInfo":       "{v} 版本中的 {n} 个配置",
        "modal.mergeBtn":         "合并到现有配置",
        "modal.overwriteAllBtn":  "覆盖全部",
        "modal.versionMismatch":  "\u26A0 版本不匹配",
        "modal.versionMismatchDesc": "此备份由版本 {version} 创建（当前版本：{current}），可能存在兼容问题。",
        "modal.areYouSure":       "确定要继续吗？",
        "modal.nameConflicts":    "名称冲突",
        "modal.conflictsDesc":    "以下配置已存在，请选择处理方式。",
        "modal.conflict":         "个冲突",
        "modal.conflicts":        "个冲突",
        "modal.confirmAll":       "全部确认",
        "modal.newBuildName":     "新配置名称...",
        "modal.nameEmpty":        "名称不能为空。",
        "modal.nameTaken":        "该名称在此武器中已存在。",
        "modal.nameDuplicate":    "此次导入中存在重复名称。",
        // About dialog
        "about.title":            "关于EFTForge",
        "about.reportBug":        "反馈问题",
        "about.disclaimer1":      "游戏内容及素材均为<strong style=\"color:#bbb;\">Battlestate Games</strong>及其授权方的商标和著作权所有。保留所有权利。",
        "about.disclaimer2":      "EFTForge是一款非官方的工具，与<strong style=\"color:#bbb;\">Battlestate Games</strong>公司无关联，未获其认可，亦不存在任何形式的官方合作关系。",
        "about.dataSource":       "所有游戏内数据来源于",
        "about.copyright":        "\u00A9 2026 Morph1ne. 保留所有权利。",
        // Toast messages
        "toast.savedTitle":           "配置已保存",
        "toast.savedMsg":             "配置已成功保存。",
        "toast.resetTitle":           "配置已重置",
        "toast.resetMsg":             "配置已恢复到出厂状态。",
        "toast.strippedTitle":        "配件已清除",
        "toast.strippedMsg":          "所有配件已移除。",
        "toast.importedTitle":        "配置已导入",
        "toast.importedMsg":          "配置导入成功。",
        "toast.exportedTitle":        "备份已导出",
        "toast.exportedMsg":          "所有配置已导出。",
        "toast.exportedCountMsg":     "已导出 {n} 个配置。",
        "toast.noBuildsToExportTitle": "无法导出",
        "toast.noBuildsToExport":     "暂无可导出的配置。",
        "modal.deletePublishedTitle": "删除已发布配置",
        "modal.deletePublishedBody":  "该配置已发布至社区。删除本地配置将同时将其从社区列表中移除。",
        "modal.deleteAndUnlist":      "删除并下架",
        "toast.deletedTitle":         "配置已删除",
        "toast.invalidCode":          "无效的配置码。",
        "toast.invalidFile":          "无效的备份文件。",
        "toast.connectionError":      "连接错误",
        "toast.backendDown":          "无法加载武器列表。",
        "toast.ammoLoadFailed":       "无法加载弹药数据。",
        "toast.serverUnreachable":    "无法连接服务器。",
        "toast.attachListFailed":     "无法加载配件列表。",
        "toast.attachDataFailed":     "无法加载配件数据。",
        "toast.networkHintDev":       "请检查后端是否正在运行。",
        "toast.networkHintProd":      "请检查您的网络连接。",
        "toast.syncNoticeTitle":      "每日数据同步",
        "toast.syncNoticeMsg":        "服务器将于每日 UTC+8 凌晨4:00 同步 tarkov.dev 数据。期间，网站可能无法访问（约1分钟）。",
        "toast.storageFull":          "存储空间已满",
        "toast.storageFullMsg":       "请删除部分已保存的配置以腾出空间。",
        "toast.saveFailed":           "保存失败",
        "toast.saveFailedMsg":        "请输入配置名称。",
        "toast.codeCopiedMsg":        "配置码已复制到剪贴板。",
        "toast.copyFailed":           "复制失败",
        "toast.clipboardFailed":      "无法访问剪贴板。",
        "toast.loadFailed":           "加载失败",
        "toast.codeCorrupted":        "配置码已损坏。",
        // Publish / unlist toasts
        "toast.publishSuccess":       "方案已发布",
        "toast.publishSuccessMsg":    "您的配件方案已向社区公开！",
        "toast.publishFailed":        "发布失败",
        "toast.publishRateLimit":     "请稍后再发布。（1分钟）",
        "toast.publishLimitReached":  "该枪械的社区配件方案已达上限，请联系网站管理员处理。",
        "toast.publishBanned":        "您已被禁止发布配件方案。",
        "toast.unlistSuccess":        "方案已下架",
        "toast.unlistSuccessMsg":     "您的配件方案已从社区移除。",
        "toast.unlistFailed":         "下架失败",
        // Publish confirm panel
        "publish.confirm":            "您即将为所有玩家发布此配件方案。",
        "publish.confirmSub":         "发布后无法修改。",
        "publish.nameWarning":        "请注意！您的自定义配置名称将会被公开，并与您的身份绑定。侮辱性、违法或滥用性名称将被管理员追溯，并承担相应后果。",
        "publish.btnCancel":          "取消",
        "publish.btnModify":          "修改",
        "publish.btnConfirm":         "确认发布",
        "publish.publishing":         "发布中...",
        "publish.mobileTray":         "查看并发布",
        "publish.slotLockedTitle":    "正在审核配置",
        "publish.slotLockedMsg":      "您正处于发布确认阶段。点击'修改'以更改配件。",
        // Admin push notifications
        "notify.bannedTitle":         "发布受限",
        "notify.banned":              "您已被临时禁止发布配件方案。封禁时长：{duration}。解封时间：{date}。",
        "notify.bannedPermanent":     "您已被永久禁止发布配件方案。",
        "notify.banReason":           "原因：{reason}",
        "notify.unbannedTitle":       "发布已恢复",
        "notify.unbanned":            "您的发布限制已解除，发布配装方案功能恢复。",
        "notify.unlistedTitle":       "方案已被移除",
        "notify.buildUnlisted":       "您的方案\"{name}\"已被管理员下架。",
        "notify.announcementTitle":   "服务器公告",
        "toast.unknownWeapon":        "配置码中包含未知武器。",
        "toast.buildLoaded":          "配置已加载",
        "toast.loadedSuffix":         " 已加载。",
        "toast.stateRestored":        "配置已恢复",
        "toast.stateRestoredMsg":     "上一次配置快照已恢复。",
        "toast.partialLoad":          "部分加载",
        "toast.partialLoadMsg":       "{n} 个配件无法找到。\n游戏数据可能已更新。",
        "toast.importFailed":         "导入失败",
        "toast.invalidBuildCode":     "无效或已损坏的配置码。",
        "toast.backupImportedTitle":  "备份已导入",
        "toast.backupLoadedMsg":      "已加载 {n} 个配置。",
        "toast.backupMergedMsg":      "已导入 {n} 个配置。",
        "toast.readFileFailed":       "无法读取备份文件。",
        "toast.pasteFailed":          "粘贴失败",
        "toast.attachmentConflict":   "配件冲突",
        "toast.mobileWarningTitle":   "检测到移动设备",
        "toast.mobileWarningMsg":     "本站针对桌面端优化。如需最佳体验，请使用电脑访问。",
        // Conflict reason prefixes
        "conflict.incompatibleWith":  "与以下配件冲突：",   
        "conflict.slot":              "配件冲突：",
        "conflict.blockedBy":         "被已安装配件阻止：",
        // UI labels
        "ui.cancel":              "取消",
        "ui.overwrite":           "覆盖",
        "ui.confirm":             "确认？",
        "ui.load":                "加载",
        "ui.copy":                "复制",
        "ui.skip":                "跳过",
        "ui.rename":              "重命名",
        "ui.continue":            "继续",
        "ui.noAmmoFound":         "未找到弹药",
        "ui.noGrenade":           "- 不装填榴弹 -",
        "ui.selectAttFor":        "选择配件：",
        "ui.compare":             "对比",
        "ui.purchasableOnly":     "可购",
        "ui.purchasableOnlyTip":  "隐藏当前商人等级无法购买的配件。在价格页面的「设置商人等级」中调整等级。",
        "ui.taskUnlock":          "任务解锁：",
        "ui.compareBaseline":     "基准",
        "ui.compareHintSelect":   "点击任意配件将其设为对比基准",
        "ui.compareHintBaseline": "已设置基准 - 悬停对比，点击更换基准",
        // Weapon class display names
        "class.Assault rifle":    "突击步枪",
        "class.Assault carbine":  "突击卡宾枪",
        "class.Marksman rifle":   "精确射手步枪",
        "class.Sniper rifle":     "狙击步枪",
        "class.Machinegun":       "轻机枪",
        "class.Machine gun":      "轻机枪",
        "class.Machine Gun":      "轻机枪",
        "class.SMG":              "冲锋枪",
        "class.Submachine gun":   "冲锋枪",
        "class.Shotgun":          "霰弹枪",
        "class.Handgun":          "手枪",
        "class.Revolver":         "左轮手枪",
        "class.Grenade launcher": "榴弹发射器",
        "class.Grenade Launcher": "榴弹发射器",
        "class.Primary":          "其他",
        // Slot names (keys match the display names returned by the tarkov.dev API)
        "slot.Barrel":            "枪管",
        "slot.Muzzle":            "枪口",
        "slot.Stock":             "枪托",
        "slot.Handguard":         "护木",
        "slot.Scope":             "瞄具",
        "slot.Front Sight":       "准星",
        "slot.Rear Sight":        "照门",
        "slot.Pistol Grip":       "手枪握把",
        "slot.Magazine":          "弹匣",
        "slot.Gas Block":         "导气管",
        "slot.Foregrip":          "前握把",
        "slot.Ch. Handle":        "拉机柄",
        "slot.Mount":             "导轨",
        "slot.Tactical":          "战术配件",
        "slot.Bipod":             "脚架",
        "slot.Receiver":          "上机匣",
        "slot.Ubgl":              "下挂榴弹发射器",
        "slot.Grip":              "握把",
        "slot.Trigger":           "扳机",
        "slot.Hammer":            "击锤",
        "slot.Chamber":           "弹膛",
        "slot.Catch":             "空仓挂机柄",
        // Attachment ratings
        "rating.like":            "这个配件真好用！",
        "rating.dislike":         "这个配件真垃圾！",
        // Build ratings
        "cb.rating.like":         "这个配置真好用！",
        // Leaderboard
        "btn.leaderboard":              "排行榜",
        "lb.title":                     "排行榜",
        "lb.builds":                    "社区方案",
        "lb.attachments":               "配件",
        "lb.period2w":                  "近两周",
        "lb.periodAll":                 "全部",
        "lb.sortLikes":                 "最多点赞",
        "lb.sortDislikes":              "最多踩",
        "lb.categoryAll":               "全部槽位",
        "lb.buildsInfo":                "近两周排名前10的配置可被提名为推荐配置，并配有完整改装预览图片，直接链接至对应配置！",
        "lb.empty":                     "暂无数据。",
        "lb.loadError":                 "无法加载排行榜。",
        "lb.top10":                     "前10名",
        "lb.top20":                     "前20名",
        "lb.top50":                     "前50名",
        "lb.top100":                    "前100名",
        "lb.likes":                     "赞",
        "lb.dislikes":                  "踩",
        "lb.buildLoaded":               "已从排行榜加载配置",
        "lb.gunFilterAll":              "全部枪械",
    },
};

function t(key) {
    const lang = (window.EFTForge.state && window.EFTForge.state.lang) || "en";
    const table = _TRANSLATIONS[lang] || _TRANSLATIONS["en"];
    return (table[key] !== undefined) ? table[key] : ((_TRANSLATIONS["en"][key] !== undefined) ? _TRANSLATIONS["en"][key] : key);
}

function tFmt(key, vars) {
    let str = t(key);
    for (const [k, v] of Object.entries(vars)) {
        str = str.replaceAll(`{${k}}`, String(v));
    }
    return str;
}

function tSlot(rawSlotName) {
    const translated = t(`slot.${rawSlotName}`);
    if (translated === `slot.${rawSlotName}`) return rawSlotName;
    return translated;
}

function tClass(rawClassName) {
    const translated = t(`class.${rawClassName}`);
    if (translated === `class.${rawClassName}`) return rawClassName;
    return translated;
}

window.EFTForge.lang = { t, tFmt, tSlot, tClass };

// Expose as globals so template literals in rendering modules can call them directly
window.t      = t;
window.tFmt   = tFmt;
window.tSlot  = tSlot;
window.tClass = tClass;
